/*!
 * comrade_jni::api — the Dart/Flutter FFI boundary, generated by
 * flutter_rust_bridge (FRB) v2.
 *
 * This is the *second* foreign ABI exported from this one cdylib. It is a
 * peer of, not a replacement for, the uniffi surface in [`crate`]: Kotlin's
 * background services (`WakeWordService`, `RelayConnectionService`,
 * `ModelDownloadService`, `CommandDispatcher`) must be able to reach Rust
 * without waking the Flutter engine, so they keep calling the uniffi
 * bindings, while the UI calls these functions from Dart.
 *
 * # One runtime, not two
 *
 * Every function here resolves [`crate::global_runtime`] — the same
 * `Arc<RwLock<ComradeRuntime>>` that `crate::Comrade` holds. That is load
 * bearing, not tidiness: `comrade_storage::EncryptedStore::open` opens the
 * vault with `redb::Database::create`, and redb takes an exclusive file lock,
 * so a second `ComradeRuntime` unlocking the same directory fails outright.
 * See `docs/FRONTEND_STRATEGY.md` §4 D2 and this crate's module header.
 *
 * # Sync vs async, and why it matters here
 *
 * FRB runs a plain `fn` on its own worker thread pool and an `async fn` on its
 * own Tokio runtime. `ComradeRuntime`'s cheap accessors use
 * `RwLock::blocking_read`/`blocking_write`, which **panic** if called from
 * inside a Tokio reactor — so those stay plain `fn` (a worker thread has no
 * ambient reactor, exactly like the JNA thread the uniffi tier is called on),
 * and only the methods that genuinely need a reactor are `async fn`. The
 * split below is deliberately identical to the one in [`crate::Comrade`].
 *
 * `#[frb(sync)]` — which runs the body *on the Dart isolate thread*, blocking
 * it — is used only for the handful of pure, allocation-cheap helpers that
 * touch no runtime state at all.
 *
 * # Regenerating the bindings
 *
 * `src/frb_generated.rs` and the Dart side are produced by:
 *
 * ```text
 * flutter_rust_bridge_codegen generate \
 *   --rust-input crate::api \
 *   --rust-root crates/comrade_jni \
 *   --dart-output <flutter-app>/lib/src/rust \
 *   --no-add-mod-to-lib --no-web
 * ```
 *
 * `--no-add-mod-to-lib` because `mod frb_generated;` is already declared by
 * hand in lib.rs, next to `uniffi::setup_scaffolding!`. The Dart package needs
 * `flutter_rust_bridge` + `freezed_annotation` as dependencies and
 * `build_runner` + `freezed` as dev-dependencies — the bridged enums
 * (`BridgeEvent`, `CallSignal`, `UiError`) generate freezed unions, and
 * codegen refuses to finish without them.
 *
 * The mirror declarations below exist because FRB only bridges types it can
 * see in the crate it parses; the DTOs live in `comrade_ui`/`comrade_core`.
 * They are a straight field-for-field restatement — **if you add a field to a
 * DTO, add it here too**, or codegen will fail with a field mismatch.
 */

use std::sync::Arc;

use comrade_ui::ComradeRuntime;
use flutter_rust_bridge::frb;
use tokio::sync::RwLock;

use crate::frb_generated::StreamSink;

// `pub use`, not `use`: the generated `frb_generated.rs` refers to every
// bridged type as `crate::api::<Name>`, so each one has to be nameable through
// this module. (Re-exporting them is harmless — this crate is a cdylib; it has
// no Rust downstream.)
pub use crate::{KeypairDto, WorkspaceKeyLabel};
pub use comrade_core::call::{CallMediaKind, CallSignal, HangupReason, IceStrategy};
pub use comrade_core::handoff::{AttachmentHandoff, AttachmentRoute, HandoffSignal};
pub use comrade_core::share::transport::{
    IcePathKind, RefusalReason, RelayPolicy, TransferVerdict,
};
pub use comrade_core::share::{ShareOffer, ShareSignal, TransferSignal};
pub use comrade_core::together::{MusicLink, Recording, StateChange, SyncVerdict, TogetherContent};
pub use comrade_ui::{
    AttachmentHandoffDto, BridgeEvent, CallRecordDto, CallSessionDto, CallSignalDto, ChitthiDto,
    ComradeDto, ContactDto, ConversationDto, CrisisResourceDto, DirectMessageDto, FoundProfileDto,
    IceServerDto, IdentityDto, JournalEntryDto, JournalRecordingDto, LinkPreviewDto, MediaBytesDto,
    MediaMessageDto, MeshStatusDto, MessageActionState, MessageAuthor, MessageDto,
    MessageRequestDto, MetricDto, PeerProfileDto, PresenceDto, PreviewKindDto, ProfileDto,
    ReactionDto, RideSignalDto, ShareVerdictDto, SharedNoteDto, TaraMessageDto, ThreadDto,
    ThreadSummaryDto, TogetherCommandDto, TogetherCorrectionDto, TogetherInviteDto,
    TogetherSessionDto, TogetherShareDto, TopicDto, TurnServerStatusDto, UiError, UpiIntentDto,
    WorkspaceDto,
};

/// The process-global runtime every function in this module reads.
///
/// `pub(crate)` rather than private so `crate`'s tests can assert — with
/// `Arc::ptr_eq` — that this ABI and the uniffi one really are looking at one
/// object. Never exported to Dart (`ComradeRuntime` is not an FRB type).
pub(crate) fn runtime() -> &'static Arc<RwLock<ComradeRuntime>> {
    crate::global_runtime()
}

/// Runs once, when the Dart side first loads the library.
///
/// `setup_default_user_utils` routes the `log` crate to logcat/oslog and
/// installs a panic hook that logs the backtrace. The hook only *observes* —
/// it does not stop unwinding — so uniffi's `catch_unwind` at the Kotlin
/// boundary still turns a panic into a `PanicException` rather than a crash.
///
/// [`crate::init_logging`] goes **first**, and the order is the point. On
/// Android both calls install a `log` sink and the first one wins for good
/// (`android_logger::init_once`): ours is warn-and-error and scoped to this
/// project's crates, frb's is TRACE and scoped to nothing. Calling ours first
/// is what keeps a user's logcat from filling with third-party trace lines.
/// This crate logs through `tracing`; on Android that reaches the same sink via
/// the `log-always` bridge (see [`crate::init_logging`]), on every other target
/// it does not and only frb's own diagnostics come through here.
#[frb(init)]
pub fn init_app() {
    crate::init_logging();
    flutter_rust_bridge::setup_default_user_utils();
}

// ── Mirrors of the DTOs that live in comrade_ui / comrade_core ───────────────
//
// FRB's parser only sees this crate, so each foreign type used in a signature
// needs a `#[frb(mirror(..))]` restatement. These generate the Dart classes;
// the real types are still the ones in comrade_ui/comrade_core.

#[frb(mirror(WorkspaceDto))]
pub struct _WorkspaceDto {
    pub key: String,
    pub label: String,
    pub active: bool,
    pub relay_connected: bool,
    pub mesh_active: bool,
    pub couple_sandbox: bool,
}

#[frb(mirror(IdentityDto))]
pub struct _IdentityDto {
    pub npub: String,
    pub has_secret: bool,
}

#[frb(mirror(UpiIntentDto))]
pub struct _UpiIntentDto {
    pub amount_inr: f64,
    pub vpa: String,
    pub uri: String,
}

#[frb(mirror(ChitthiDto))]
pub struct _ChitthiDto {
    pub id: String,
    pub author: String,
    pub content: String,
    pub created_at: u64,
    pub reply_to: Option<String>,
}

#[frb(mirror(DirectMessageDto))]
pub struct _DirectMessageDto {
    pub id: String,
    pub sender: String,
    pub content: String,
    pub created_at: u64,
    pub upi_intents: Vec<UpiIntentDto>,
    pub reply_to: Option<String>,
    pub shared_note: Option<SharedNoteDto>,
}

#[frb(mirror(MessageAuthor))]
pub enum _MessageAuthor {
    Human,
    Tara,
}

#[frb(mirror(MessageDto))]
pub struct _MessageDto {
    pub id: String,
    pub peer: String,
    pub content: String,
    pub created_at: u64,
    pub outgoing: bool,
    pub author: MessageAuthor,
    pub status: Option<String>,
    pub reply_to: Option<String>,
    pub shared_note: Option<SharedNoteDto>,
    pub link_preview: Option<LinkPreviewDto>,
    pub forwarded: bool,
    pub actions: MessageActionState,
}

#[frb(mirror(MessageActionState))]
pub struct _MessageActionState {
    pub starred: bool,
    pub pinned: bool,
}

// No `image_url` here — deliberately. See the field-removal note on
// `comrade_ui::runtime::LinkPreviewDto`: a URL on the linked host must not
// cross this boundary, or a frontend rendering it as `<img src=…>` tells that
// host which npub read the link, defeating the zero-network-request design.
#[frb(mirror(LinkPreviewDto))]
pub struct _LinkPreviewDto {
    pub url: String,
    pub canonical_url: String,
    pub title: Option<String>,
    pub description: Option<String>,
    pub site_name: Option<String>,
    pub kind: PreviewKindDto,
    pub display_domain: Option<String>,
}

#[frb(mirror(PreviewKindDto))]
pub enum _PreviewKindDto {
    Article,
    Photo,
    Video,
    Profile,
    Unknown,
}

#[frb(mirror(SharedNoteDto))]
pub struct _SharedNoteDto {
    pub text: String,
    pub mood: Option<String>,
}

#[frb(mirror(TopicDto))]
pub struct _TopicDto {
    pub slug: String,
    pub name: String,
    pub peer: String,
    pub created_by: String,
    pub mine: bool,
    pub created_at: u64,
    pub closed: bool,
    pub thread_count: u32,
    pub message_count: u32,
    pub last_activity_at: u64,
}

#[frb(mirror(ThreadSummaryDto))]
pub struct _ThreadSummaryDto {
    pub root_id: String,
    pub peer: String,
    pub topic_slug: Option<String>,
    pub preview: String,
    pub root_is_media: bool,
    pub root_missing: bool,
    pub started_at: u64,
    pub reply_count: u32,
    pub last_at: u64,
    pub unread: bool,
}

#[frb(mirror(ThreadDto))]
pub struct _ThreadDto {
    pub root_id: String,
    pub peer: String,
    pub topic_slug: Option<String>,
    pub messages: Vec<MessageDto>,
    pub media: Vec<MediaMessageDto>,
}

#[frb(mirror(ConversationDto))]
pub struct _ConversationDto {
    pub peer: String,
    pub alias: Option<String>,
    pub peer_name: Option<String>,
    pub last_message: String,
    pub last_at: u64,
    pub last_outgoing: bool,
    pub comrade: bool,
    pub online: bool,
}

#[frb(mirror(MessageRequestDto))]
pub struct _MessageRequestDto {
    pub peer: String,
    pub last_message: String,
    pub last_at: u64,
}

#[frb(mirror(ProfileDto))]
pub struct _ProfileDto {
    pub npub: String,
    pub username: Option<String>,
    pub about: Option<String>,
    pub picture: Option<String>,
    pub avatar_cached: bool,
}

#[frb(mirror(FoundProfileDto))]
pub struct _FoundProfileDto {
    pub npub: String,
    pub name: Option<String>,
    pub about: Option<String>,
    pub picture: Option<String>,
    pub nip05: Option<String>,
}

#[frb(mirror(PeerProfileDto))]
pub struct _PeerProfileDto {
    pub npub: String,
    pub alias: String,
    pub name: Option<String>,
    pub about: Option<String>,
    pub picture: Option<String>,
    pub nip05: Option<String>,
    pub lud16: Option<String>,
    pub avatar_cached: bool,
    pub contact: bool,
    pub comrade: bool,
    pub blocked: bool,
    pub online: bool,
    pub last_seen_at: u64,
    pub peer_marked_us: bool,
    pub updated_at: u64,
}

#[frb(mirror(ContactDto))]
pub struct _ContactDto {
    pub npub: String,
    pub alias: String,
    pub name: Option<String>,
    pub comrade: bool,
}

#[frb(mirror(ComradeDto))]
pub struct _ComradeDto {
    pub npub: String,
    pub alias: String,
    pub name: Option<String>,
    pub online: bool,
    pub last_seen_at: u64,
    pub peer_marked_us: bool,
}

#[frb(mirror(PresenceDto))]
pub struct _PresenceDto {
    pub peer: String,
    pub online: bool,
    pub last_seen_at: u64,
    pub peer_marked_us: bool,
}

#[frb(mirror(MetricDto))]
pub struct _MetricDto {
    pub key: String,
    pub value: u64,
}

#[frb(mirror(JournalEntryDto))]
pub struct _JournalEntryDto {
    pub id: String,
    pub title: Option<String>,
    pub text: String,
    pub mood: Option<String>,
    pub recording: Option<JournalRecordingDto>,
    pub created_at: u64,
}

#[frb(mirror(JournalRecordingDto))]
pub struct _JournalRecordingDto {
    pub file_name: String,
    pub mime: String,
    pub duration_ms: u64,
    pub size_bytes: u64,
}

#[frb(mirror(TaraMessageDto))]
pub struct _TaraMessageDto {
    pub id: String,
    pub text: String,
    pub from_tara: bool,
    pub crisis: bool,
    pub created_at: u64,
}

#[frb(mirror(CrisisResourceDto))]
pub struct _CrisisResourceDto {
    pub name: String,
    pub contact: String,
    pub note: String,
}

#[frb(mirror(IceServerDto))]
pub struct _IceServerDto {
    pub urls: Vec<String>,
    pub username: Option<String>,
    pub credential: Option<String>,
}

#[frb(mirror(TurnServerStatusDto))]
pub struct _TurnServerStatusDto {
    pub configured: bool,
    pub url: Option<String>,
}

#[frb(mirror(CallSessionDto))]
pub struct _CallSessionDto {
    pub call_id: String,
    pub peer: String,
    pub media: String,
    pub ice_servers: Vec<IceServerDto>,
}

#[frb(mirror(CallSignalDto))]
pub struct _CallSignalDto {
    pub call_id: String,
    pub peer: String,
    pub media: String,
    pub signal: CallSignal,
    pub created_at: u64,
}

#[frb(mirror(CallRecordDto))]
pub struct _CallRecordDto {
    pub id: String,
    pub peer: String,
    pub media: String,
    pub incoming: bool,
    pub outcome: String,
    pub started_at: u64,
    pub duration_secs: u64,
}

#[frb(mirror(MediaMessageDto))]
pub struct _MediaMessageDto {
    pub event_id: String,
    pub url: String,
    pub mime_type: String,
    pub caption: String,
    pub sender: String,
    pub created_at: u64,
    pub size: u64,
    pub outgoing: bool,
}

#[frb(mirror(ReactionDto))]
pub struct _ReactionDto {
    pub target_id: String,
    pub peer: String,
    pub reactor: String,
    pub emoji: String,
    pub created_at: u64,
    pub outgoing: bool,
}

#[frb(mirror(MediaBytesDto))]
pub struct _MediaBytesDto {
    pub mime_type: String,
    pub base64: String,
}

#[frb(mirror(MeshStatusDto))]
pub struct _MeshStatusDto {
    pub active: bool,
    pub peer_count: u64,
}

// `crate::KeypairDto` and `crate::WorkspaceKeyLabel` are declared in this same
// crate (they are uniffi `Record`s in lib.rs), so FRB's parser already sees
// them through `cargo expand` and bridges them directly — mirroring them here
// too would give the codegen two objects under one key.

#[frb(mirror(CallMediaKind))]
pub enum _CallMediaKind {
    Audio,
    Video,
}

#[frb(mirror(HangupReason))]
pub enum _HangupReason {
    Normal,
    Declined,
    Busy,
    Missed,
    Cancelled,
    Failed,
    Unknown,
}

#[frb(mirror(IceStrategy))]
pub enum _IceStrategy {
    StunOnly,
    StunAndTurn,
}

#[frb(mirror(CallSignal))]
pub enum _CallSignal {
    Offer {
        sdp: String,
    },
    Answer {
        sdp: String,
    },
    Ice {
        candidate: String,
        sdp_mid: Option<String>,
        sdp_m_line_index: Option<u16>,
    },
    Ringing,
    Busy,
    Hangup {
        reason: HangupReason,
    },
}

#[frb(mirror(IcePathKind))]
pub enum _IcePathKind {
    Host,
    ServerReflexive,
    Relay,
    Unknown,
}

#[frb(mirror(RelayPolicy))]
pub enum _RelayPolicy {
    DirectOnly,
    UnderBytes { limit: u64 },
    AskEachTime,
    Always,
}

#[frb(mirror(RefusalReason))]
pub enum _RefusalReason {
    RelayForbidden,
    TooLargeForRelay { limit: u64 },
    PathUnknown,
}

#[frb(mirror(TransferVerdict))]
pub enum _TransferVerdict {
    Allow,
    NeedsConsent { relayed_bytes: u64 },
    Refuse { reason: RefusalReason },
}

#[frb(mirror(Recording))]
pub struct _Recording {
    pub isrc: Option<String>,
    pub title: String,
    pub artist: String,
    pub album: Option<String>,
}

#[frb(mirror(MusicLink))]
pub enum _MusicLink {
    Spotify {
        track_id: String,
    },
    AppleMusic {
        storefront: String,
        track_id: String,
    },
    Youtube {
        video_id: String,
    },
}

#[frb(mirror(TogetherContent))]
pub enum _TogetherContent {
    LocalFile {
        duration_ms: u64,
        recording: Option<Recording>,
    },
    Youtube {
        video_id: String,
    },
    Service {
        link: MusicLink,
        recording: Option<Recording>,
    },
    Stream {
        url: String,
        recording: Option<Recording>,
        duration_ms: Option<u64>,
    },
}

#[frb(mirror(SyncVerdict))]
pub enum _SyncVerdict {
    Hold,
    Adopt {
        pos_ms: u64,
        playing: bool,
        seq: u64,
    },
    Nudge {
        rate: f64,
    },
    Seek {
        pos_ms: u64,
    },
}

#[frb(mirror(StateChange))]
pub enum _StateChange {
    Played,
    Paused,
    Seeked,
    PausedAndSeeked,
    Unchanged,
}

#[frb(mirror(TogetherInviteDto))]
pub struct _TogetherInviteDto {
    pub session_id: String,
    pub peer: String,
    pub content: TogetherContent,
    pub pos_ms: u64,
    pub playing: bool,
    pub created_at: u64,
}

#[frb(mirror(TogetherSessionDto))]
pub struct _TogetherSessionDto {
    pub session_id: String,
    pub peer: String,
    pub content: TogetherContent,
    pub we_lead: bool,
    pub joined: bool,
    pub pos_ms: u64,
    pub playing: bool,
}

#[frb(mirror(TogetherCommandDto))]
pub struct _TogetherCommandDto {
    pub session_id: String,
    pub pos_ms: u64,
    pub playing: bool,
    pub change: StateChange,
    pub apply_in_ms: u64,
}

#[frb(mirror(TogetherCorrectionDto))]
pub struct _TogetherCorrectionDto {
    pub session_id: String,
    pub verdict: SyncVerdict,
    pub drift_ms: i64,
    pub quality_ms: u64,
}

#[frb(mirror(ShareOffer))]
pub struct _ShareOffer {
    pub total_bytes: u64,
    pub chunk_bytes: u32,
    pub sha256: String,
    pub duration_ms: u64,
}

#[frb(mirror(TransferSignal))]
pub enum _TransferSignal {
    Offer {
        sdp: String,
    },
    Answer {
        sdp: String,
    },
    Ice {
        candidate: String,
        sdp_mid: Option<String>,
        sdp_m_line_index: Option<u16>,
    },
}

#[frb(mirror(ShareSignal))]
pub enum _ShareSignal {
    Ask,
    Offer { offer: ShareOffer },
    Accept,
    Refuse { reason: RefusalReason },
    Transport { signal: TransferSignal },
}

#[frb(mirror(TogetherShareDto))]
pub struct _TogetherShareDto {
    pub session_id: String,
    pub peer: String,
    pub signal: ShareSignal,
}

#[frb(mirror(AttachmentHandoff))]
pub struct _AttachmentHandoff {
    pub shape: ShareOffer,
    pub mime_type: String,
    pub file_name: String,
    pub caption: String,
}

#[frb(mirror(HandoffSignal))]
pub enum _HandoffSignal {
    Offer { attachment: AttachmentHandoff },
    Accept,
    Decline,
    Refuse { reason: RefusalReason },
    Withdraw,
    Transport { signal: TransferSignal },
}

#[frb(mirror(AttachmentRoute))]
pub enum _AttachmentRoute {
    Hosted,
    PeerToPeer,
}

#[frb(mirror(AttachmentHandoffDto))]
pub struct _AttachmentHandoffDto {
    pub transfer_id: String,
    pub peer: String,
    pub signal: HandoffSignal,
}

#[frb(mirror(ShareVerdictDto))]
pub struct _ShareVerdictDto {
    pub verdict: String,
    pub path: String,
    pub reason: Option<RefusalReason>,
    pub relayed_bytes: Option<u64>,
}

#[frb(mirror(RideSignalDto))]
pub struct _RideSignalDto {
    pub peer: String,
    pub name: Option<String>,
    pub kind: String,
    pub phrase: Option<String>,
    pub maneuver: Option<String>,
    pub distance_m: Option<u32>,
    pub note: Option<String>,
    pub urgency: String,
    pub created_at: u64,
}

#[frb(mirror(BridgeEvent))]
pub enum _BridgeEvent {
    IncomingChitthi(ChitthiDto),
    IncomingDirectMessage(DirectMessageDto),
    IncomingMedia(MediaMessageDto),
    IncomingReaction(ReactionDto),
    IncomingCallSignal(CallSignalDto),
    IncomingMessageRequest(MessageRequestDto),
    MessageStatus {
        peer: String,
        message_ids: Vec<String>,
        status: String,
    },
    PeerProfileUpdated {
        peer: String,
        name: Option<String>,
    },
    ComradePresence {
        peer: String,
        name: Option<String>,
        online: bool,
        at: u64,
    },
    ComradeNudge {
        peer: String,
        name: Option<String>,
    },
    RideSignal(RideSignalDto),
    TogetherInvited(TogetherInviteDto),
    TogetherJoined {
        session_id: String,
        peer: String,
    },
    TogetherCommand(TogetherCommandDto),
    TogetherCorrection(TogetherCorrectionDto),
    TogetherEnded {
        session_id: String,
        peer: String,
        by_peer: bool,
    },
    TogetherShare(TogetherShareDto),
    TogetherOutbound {
        session_id: String,
        json: String,
    },
    AttachmentHandoff(AttachmentHandoffDto),
    MeshStatusChanged(MeshStatusDto),
    LedgerUpdated {
        ledger: String,
    },
    TopicsChanged {
        peer: String,
    },
}

#[frb(mirror(UiError))]
pub enum _UiError {
    UnknownWorkspace(String),
    Transition(String),
    NoIdentity,
    StoreLocked,
    Crypto(String),
    Storage(String),
    VaultLocked,
    Engine(String),
    Catalogue(String),
    Download(String),
    CatalogueUnavailable,
    Travel(String),
    TravelUnavailable,
}

// ── Stateless helpers (no runtime needed) ────────────────────────────────────
//
// `#[frb(sync)]`: pure, microsecond-scale, and called from build methods, so
// paying a Dart `Future` round-trip for them would be silly. Nothing here
// touches the runtime lock, so blocking the isolate thread is free.

/// The comrade_jni crate version (e.g. "0.1.0").
#[frb(sync)]
pub fn version() -> String {
    crate::version()
}

/// A freshly generated secp256k1 keypair, Bech32-encoded. Standalone — doesn't
/// touch the encrypted store; see [`generate_identity`] and [`unlock_vault`]
/// for the store-backed identity flow every UI screen actually drives.
#[frb(sync)]
pub fn generate_keypair() -> Result<KeypairDto, UiError> {
    crate::generate_keypair()
}

/// Derive the npub from an nsec Bech32 string, or `None` if it doesn't parse.
#[frb(sync)]
pub fn npub_from_nsec(nsec: String) -> Option<String> {
    crate::npub_from_nsec(nsec)
}

/// The display label for a workspace discriminant, or `None` for an unknown key.
#[frb(sync)]
pub fn workspace_label(workspace: String) -> Option<String> {
    crate::workspace_label(workspace)
}

/// Every workspace discriminant and its label — a stable, store-free list
/// (contrast [`workspaces`], which also reports which one is active).
#[frb(sync)]
pub fn all_workspaces() -> Vec<WorkspaceKeyLabel> {
    crate::all_workspaces()
}

// ── Runtime lifecycle ────────────────────────────────────────────────────────

/// Materialise the process-global runtime, if some other caller (e.g. Kotlin
/// constructing `Comrade()`) has not already. The Dart counterpart of
/// `Comrade()`; there is no handle to hold onto because there is nothing to
/// hold — every function below finds the same runtime on its own.
pub fn init_runtime() {
    let _ = runtime();
}

/// [`init_runtime`], but seeding the runtime with an explicit relay set —
/// AUDIT.md COMMS-03's isolated-relay test hook. Only takes effect if this is
/// what first creates the runtime; the shipping app calls [`init_runtime`].
pub fn init_runtime_with_relays(relays: Vec<String>) {
    let _ = crate::global_runtime_with_relays(relays);
}

/// Open the encrypted store, restore or seed the identity, build the engines,
/// and start the background feed/DM loops. Safe to call more than once
/// (returns the already-loaded identity) — including when the *other* ABI
/// already unlocked it, which is the whole point of the shared runtime.
pub async fn unlock_vault(path: String, passphrase: String) -> Result<IdentityDto, UiError> {
    let mut guard = runtime().write().await;
    let identity = guard.unlock_vault(&path, &passphrase).await?;
    guard.spawn_event_loops();
    Ok(identity)
}

pub async fn is_vault_unlocked() -> bool {
    runtime().read().await.is_vault_unlocked()
}

pub async fn is_store_unlocked() -> bool {
    runtime().read().await.is_store_unlocked()
}

/// Re-lock the vault: abort the background feed/DM/sakha loops and drop the
/// store, engines, and in-memory identity.
pub async fn lock_vault() {
    runtime().write().await.lock_vault().await
}

// ── Identity ─────────────────────────────────────────────────────────────────

pub fn generate_identity() -> Result<IdentityDto, UiError> {
    runtime().blocking_write().generate_identity()
}

pub fn current_identity() -> Option<IdentityDto> {
    runtime().blocking_read().current_identity()
}

pub fn extract_payments(text: String) -> Result<Vec<UpiIntentDto>, UiError> {
    runtime().blocking_read().extract_payments(&text)
}

// ── Workspace controller ─────────────────────────────────────────────────────

pub fn workspaces() -> Vec<WorkspaceDto> {
    runtime().blocking_read().workspaces()
}

pub fn current_workspace() -> WorkspaceDto {
    runtime().blocking_read().current_workspace()
}

/// Async because switching also starts/stops the Saathi mesh engine to match.
pub async fn toggle_workspace(target: String) -> Result<WorkspaceDto, UiError> {
    runtime().write().await.toggle_workspace(&target).await
}

/// Async for the same reason as [`toggle_workspace`].
pub async fn back() -> WorkspaceDto {
    runtime().write().await.back().await
}

/// Snapshot of the off-grid Saathi mesh's live status, for seeding a
/// connectivity indicator before the first `BridgeEvent::MeshStatusChanged`
/// arrives. Never fails: the mesh being off is a valid, common state.
pub fn mesh_status() -> MeshStatusDto {
    runtime().blocking_read().mesh_status()
}

// ── Sabha (public feed) ──────────────────────────────────────────────────────

pub fn fetch_sabha_timeline() -> Result<Vec<ChitthiDto>, UiError> {
    runtime().blocking_read().fetch_sabha_timeline()
}

/// Takes a cheap, synchronous handle snapshot under the guard and runs the
/// relay round-trip after it is dropped — AUDIT P2: never hold the runtime
/// lock across a network await, or one slow relay stalls every other call.
pub async fn broadcast_chitthi(
    content: String,
    reply_to: Option<String>,
) -> Result<String, UiError> {
    let handles = runtime().read().await.handles();
    handles.broadcast_chitthi(&content, reply_to).await
}

/// Broadcast a Chitthi under a throwaway or scoped persona instead of this
/// device's identity — the anonymous-thoughts path.
///
/// `scope` of `None` signs the post with a key used exactly once, so two
/// anonymous Chitthis cannot be linked to each other. `Some(label)` derives a
/// stable persona for that label, so replies can reach the same pseudonym while
/// it stays unlinkable to the identity. See `docs/BITCHAT_ADOPTION.md` for what
/// this does and does not hide.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn broadcast_anonymous_chitthi(
    content: String,
    scope: Option<String>,
) -> Result<String, UiError> {
    let handles = runtime().read().await.handles();
    handles
        .broadcast_anonymous_chitthi(&content, scope.as_deref())
        .await
}

// ── Vault (E2E DMs) ──────────────────────────────────────────────────────────

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn send_dm(target: String, content: String) -> Result<MessageDto, UiError> {
    let handles = runtime().read().await.handles();
    handles.send_dm(&target, &content).await
}

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn send_dm_reply(
    target: String,
    content: String,
    reply_to: Option<String>,
) -> Result<MessageDto, UiError> {
    let handles = runtime().read().await.handles();
    handles
        .send_dm_reply(&target, &content, reply_to.as_deref())
        .await
}

/// React to a message in `peer`'s thread — or take an existing reaction back by
/// passing the same emoji again. Returns the reaction now standing, or `None` if
/// the tap withdrew one.
///
/// The toggle is decided on the Rust side (see `ComradeRuntime::toggle_reaction`)
/// so this frontend and Android cannot disagree about what tapping an
/// already-sent emoji means.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn toggle_reaction(
    peer: String,
    target_id: String,
    emoji: String,
) -> Result<Option<ReactionDto>, UiError> {
    let handles = runtime().read().await.handles();
    handles.toggle_reaction(&peer, &target_id, &emoji).await
}

/// Every reaction in `peer`'s conversation, oldest first, read from the encrypted
/// store — so a thread opens with its reactions already drawn.
pub async fn reactions(peer: String) -> Result<Vec<ReactionDto>, UiError> {
    runtime().read().await.reactions(&peer)
}

/// Retry every DM sitting in the sender outbox because no relay would take it.
/// Returns how many a relay accepted this pass.
///
/// A background loop already flushes on a cadence (and once at launch); call
/// this when the platform reports connectivity came back, so a queued message
/// goes out immediately instead of on the next tick.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn flush_outbox() -> Result<u64, UiError> {
    let handles = runtime().read().await.handles();
    handles.flush_outbox().await.map(|n| n as u64)
}

/// How many DMs are waiting for a relay that will take them — for a "queued"
/// indicator in the chat list.
pub fn outbox_pending() -> u64 {
    runtime().blocking_read().outbox_pending() as u64
}

/// **Panic wipe.** Destroy every locally stored value — identity keys, DM
/// history, journal, Tara thread, queued mail — then re-lock, leaving the
/// runtime as it was before its first unlock.
///
/// Irreversible, and deliberately not a duress feature: it wipes rather than
/// hides, and it needs the app open and unlocked. After it returns, send the
/// user back to onboarding.
pub async fn panic_wipe() -> Result<(), UiError> {
    runtime().write().await.panic_wipe().await
}

/// Device-local delivery counters — bare tallies with no identities, ids,
/// content, or timestamps, for a diagnostics screen. Nothing here is ever
/// uploaded; [`panic_wipe`] clears them.
pub fn metrics_snapshot() -> Vec<MetricDto> {
    runtime().blocking_read().metrics_snapshot()
}

pub fn conversations() -> Result<Vec<ConversationDto>, UiError> {
    runtime().blocking_read().conversations()
}

pub fn messages_with(peer: String) -> Result<Vec<MessageDto>, UiError> {
    runtime().blocking_read().messages_with(&peer)
}

/// Every pinned message in `peer`'s conversation, oldest pin first. See
/// `comrade_ui::ComradeRuntime::pinned_messages`.
pub fn pinned_messages(peer: String) -> Result<Vec<MessageDto>, UiError> {
    runtime().blocking_read().pinned_messages(&peer)
}

/// Every starred message across every conversation, oldest star first — the
/// "Starred Messages" screen. See `comrade_ui::ComradeRuntime::starred_messages`.
pub fn starred_messages() -> Result<Vec<MessageDto>, UiError> {
    runtime().blocking_read().starred_messages()
}

/// Star or un-star one of `peer`'s messages. Local device state only; returns
/// whether the stored state changed. See
/// `comrade_ui::ComradeRuntime::star_message`.
pub fn star_message(peer: String, message_id: String, starred: bool) -> Result<bool, UiError> {
    runtime()
        .blocking_read()
        .star_message(&peer, &message_id, starred)
}

/// Pin one of `peer`'s messages. Refuses once the conversation is already at
/// the pin cap — unpin one first. `false` (not an error) if it was already
/// pinned. See `comrade_ui::ComradeRuntime::pin_message`.
pub fn pin_message(peer: String, message_id: String) -> Result<bool, UiError> {
    runtime().blocking_read().pin_message(&peer, &message_id)
}

/// Unpin one of `peer`'s messages. `true` if it was pinned. See
/// `comrade_ui::ComradeRuntime::unpin_message`.
pub fn unpin_message(peer: String, message_id: String) -> Result<bool, UiError> {
    runtime().blocking_read().unpin_message(&peer, &message_id)
}

/// Hide one of `peer`'s messages on this device only. See
/// `comrade_ui::ComradeRuntime::delete_message_for_me`.
pub fn delete_message_for_me(peer: String, message_id: String) -> Result<(), UiError> {
    runtime()
        .blocking_read()
        .delete_message_for_me(&peer, &message_id)
}

/// Delete a message you sent for everyone in `peer`'s conversation — a
/// best-effort courtesy, not a protocol guarantee. See
/// `comrade_ui::ComradeRuntime::delete_message_for_everyone`.
///
/// Not wrapped through [`broadcast_chitthi`]'s `handles()` snapshot:
/// `comrade_ui::ComradeRuntime::delete_message_for_everyone` takes `&self`
/// rather than exposing a `RuntimeHandles` counterpart, so this holds a
/// shared read guard across its network send — the same shape as
/// [`panic_wipe`], not the exclusive-write case that one guards against.
pub async fn delete_message_for_everyone(peer: String, message_id: String) -> Result<(), UiError> {
    runtime()
        .read()
        .await
        .delete_message_for_everyone(&peer, &message_id)
        .await
}

/// Forward one of `from_peer`'s messages to each of `to_peers`, as a new
/// message in each conversation. See
/// `comrade_ui::ComradeRuntime::forward_message`.
///
/// Same lock-discipline note as [`delete_message_for_everyone`]: no
/// `RuntimeHandles` counterpart exists for this one either.
pub async fn forward_message(
    from_peer: String,
    message_id: String,
    to_peers: Vec<String>,
) -> Result<Vec<MessageDto>, UiError> {
    runtime()
        .read()
        .await
        .forward_message(&from_peer, &message_id, &to_peers)
        .await
}

/// Fetch and build a link preview for the first link in `content`, if any —
/// sender-side only, run before a send. Takes no lock: a free function
/// underneath, so this wrapper cannot hold a guard across the network round
/// trip. See `comrade_ui::compose_link_preview`.
pub async fn compose_link_preview(content: String) -> Option<LinkPreviewDto> {
    comrade_ui::compose_link_preview(&content).await
}

/// Attach `preview` to `content`, producing the body [`send_dm`] should
/// actually send. See `comrade_ui::attach_link_preview`.
#[frb(sync)]
pub fn attach_link_preview(content: String, preview: LinkPreviewDto) -> String {
    comrade_ui::attach_link_preview(&content, &preview)
}

/// Full encrypted-media history with `peer`, oldest first — the media
/// counterpart of [`messages_with`].
pub fn media_with(peer: String) -> Result<Vec<MediaMessageDto>, UiError> {
    runtime().blocking_read().media_with(&peer)
}

// ── Threads and topics (see `comrade_core::topic`) ───────────────────────────

/// Every topic in `peer`'s conversation, oldest first, with live counts.
/// Closed ones are included — the archive has to be reachable.
pub fn topics(peer: String) -> Result<Vec<TopicDto>, UiError> {
    runtime().blocking_read().topics(&peer)
}

/// Every thread in `peer`'s conversation, most recently active first.
/// `topic_slug` of `None` is *all* threads, not the unfiled ones.
pub fn threads(peer: String, topic_slug: Option<String>) -> Result<Vec<ThreadSummaryDto>, UiError> {
    runtime().blocking_read().threads(&peer, topic_slug)
}

/// One thread in full. `root_id` may name any message in it — the walk up the
/// reply chain happens on the Rust side so the frontends cannot disagree about
/// which thread a bubble belongs to.
pub fn thread(peer: String, root_id: String) -> Result<ThreadDto, UiError> {
    runtime().blocking_read().thread(&peer, &root_id)
}

/// The id of the thread a message belongs to.
pub fn thread_root(peer: String, message_id: String) -> Result<String, UiError> {
    runtime().blocking_read().thread_root(&peer, &message_id)
}

/// Name a topic and tell the peer. Idempotent: naming one that exists returns
/// it, because the slug is the id.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn create_topic(peer: String, name: String) -> Result<TopicDto, UiError> {
    let handles = runtime().read().await.handles();
    handles.create_topic(&peer, &name).await
}

/// File the thread containing `message_id` under `topic_name`, creating the
/// topic if it is new — or, with `None`, take it out of wherever it was.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn assign_thread(
    peer: String,
    message_id: String,
    topic_name: Option<String>,
) -> Result<ThreadSummaryDto, UiError> {
    let handles = runtime().read().await.handles();
    handles.assign_thread(&peer, &message_id, topic_name).await
}

/// Archive a topic, or bring it back.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn set_topic_closed(
    peer: String,
    slug: String,
    closed: bool,
) -> Result<TopicDto, UiError> {
    let handles = runtime().read().await.handles();
    handles.set_topic_closed(&peer, &slug, closed).await
}

/// Reply inside a thread — addressed to the thread's root, whichever message in
/// it the caller happens to name.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn send_thread_reply(
    peer: String,
    root_id: String,
    content: String,
) -> Result<MessageDto, UiError> {
    let handles = runtime().read().await.handles();
    handles.send_thread_reply(&peer, &root_id, &content).await
}

// ── Message requests (stranger gating) + receipts ────────────────────────────

pub fn message_requests() -> Result<Vec<MessageRequestDto>, UiError> {
    runtime().blocking_read().message_requests()
}

/// Async because accepting fires a background profile-share + receipt send
/// that needs a live reactor to `tokio::spawn` onto.
pub async fn accept_request(peer: String) -> Result<(), UiError> {
    runtime().read().await.accept_request(&peer)
}

pub fn block_conversation(peer: String) -> Result<(), UiError> {
    runtime().blocking_read().block_conversation(&peer)
}

/// Async for the same reason as [`accept_request`].
///
/// Returns the read position the thread had *before* this call (unix seconds,
/// 0 = never opened), so the UI can open at the first unread message.
pub async fn mark_conversation_read(peer: String) -> Result<u64, UiError> {
    runtime().read().await.mark_conversation_read(&peer)
}

// ── Profile & contacts ───────────────────────────────────────────────────────

pub fn profile() -> Result<ProfileDto, UiError> {
    runtime().blocking_read().profile()
}

pub async fn set_username(name: String) -> Result<ProfileDto, UiError> {
    runtime().write().await.set_username(&name).await
}

/// Set (or clear, with an empty string) this identity's bio, and republish.
pub async fn set_about(about: String) -> Result<ProfileDto, UiError> {
    runtime().write().await.set_about(&about).await
}

/// Everything a profile page draws for one peer, from the local cache alone —
/// no relay round trip, so it answers offline and immediately.
pub fn peer_profile(npub: String) -> Result<PeerProfileDto, UiError> {
    runtime().blocking_read().peer_profile(&npub)
}

/// A peer's cached avatar bytes, or `None` to draw initials. Reads the encrypted
/// store and never the network, so calling it discloses nothing to anyone.
pub fn peer_avatar(npub: String) -> Result<Option<MediaBytesDto>, UiError> {
    runtime().blocking_read().peer_avatar(&npub)
}

/// Whether peer-published pictures may be fetched at all (default on).
pub fn remote_avatars_enabled() -> Result<bool, UiError> {
    runtime().blocking_read().remote_avatars_enabled()
}

pub fn set_remote_avatars_enabled(on: bool) -> Result<(), UiError> {
    runtime().blocking_read().set_remote_avatars_enabled(on)
}

pub fn add_contact(npub: String, alias: String) -> Result<ContactDto, UiError> {
    runtime().blocking_read().add_contact(&npub, &alias)
}

pub fn set_contact_alias(npub: String, alias: String) -> Result<ContactDto, UiError> {
    runtime().blocking_read().set_contact_alias(&npub, &alias)
}

pub fn remove_contact(npub: String) -> Result<bool, UiError> {
    runtime().blocking_read().remove_contact(&npub)
}

pub fn list_contacts() -> Result<Vec<ContactDto>, UiError> {
    runtime().blocking_read().list_contacts()
}

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn search_profiles(query: String) -> Result<Vec<FoundProfileDto>, UiError> {
    let handles = runtime().read().await.handles();
    handles.search_profiles(&query).await
}

/// Detaches the refresher and drops the shared lock before the relay
/// round-trip (AUDIT P2).
pub async fn refresh_peer_profiles() -> Result<u64, UiError> {
    let refresher = runtime().read().await.profile_refresher()?;
    let changed = refresher.run().await?;
    Ok(changed as u64)
}

// ── Comrades (chosen-peer presence) ──────────────────────────────────────────

/// Choose (or un-choose) a contact as a comrade.
///
/// What this discloses, stated plainly: from now on this device tells *that one
/// peer* — nobody else, and no relay — when it is online, and it starts
/// believing what they say about their own presence. It does **not** subscribe
/// us to theirs; we see them only once they have marked us back, which is what
/// [`ComradeDto`]'s `peer_marked_us` is for.
///
/// Async for the same reason as [`accept_request`]: the beacon telling that
/// peer about the change is a background `tokio::spawn`, which needs a live
/// reactor.
pub async fn set_comrade(npub: String, comrade: bool) -> Result<ContactDto, UiError> {
    runtime().read().await.set_comrade(&npub, comrade)
}

/// Every comrade with their live presence, online first.
pub fn comrades() -> Result<Vec<ComradeDto>, UiError> {
    runtime().blocking_read().comrades()
}

/// One peer's live presence, or `None` if no beacon ever arrived from them
/// (they haven't chosen us back, or haven't been online since).
pub fn peer_presence(npub: String) -> Result<Option<PresenceDto>, UiError> {
    runtime().blocking_read().peer_presence(&npub)
}

/// Announce this device's presence to every comrade, returning how many beacons
/// a relay accepted. Frontends call this on foreground/background transitions;
/// the native heartbeat covers the rest. Never fails — presence is a courtesy,
/// so a locked vault is a quiet `0`, not an error.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn announce_presence(online: bool) -> u64 {
    let handles = runtime().read().await.handles();
    handles.announce_presence(online).await
}

// ── The nudge (abandoned drafts — see `comrade_core::nudge`) ─────────────────

/// There is unsent text in `peer`'s composer, as of now.
///
/// What this discloses, stated plainly: nothing, yet. It starts a local clock.
/// If the draft is later abandoned — cleared, or left behind when the thread
/// closes — and `peer` is a comrade, their device is told *that it happened*
/// and nothing else: never the text, its length, or how the writing ended.
/// See `comrade_core::nudge` for every rule that has to agree first.
///
/// Cheap enough to call on a keystroke, and infallible: a courtesy signal has
/// no business raising an error into a text field. Synchronous for the same
/// reason — the work is a hash-map insert, so an async hop would cost more than
/// the thing it was scheduling.
///
/// `try_read` rather than a blocking acquire: nothing about watching a composer
/// is worth waiting behind a slow `lock_vault`/`unlock_vault` for, and a skipped
/// report costs at most one nudge (the next keystroke reports again).
pub fn note_draft(peer: String) {
    if let Ok(rt) = runtime().try_read() {
        rt.note_draft(&peer);
    }
}

/// That draft is gone — cleared, or left behind when the thread closed. Call it
/// whenever a conversation closes; a composer that never held text does
/// nothing.
///
/// Skipped under contention like [`note_draft`], which fails in the harmless
/// direction: locking the vault clears the watch regardless.
pub fn abandon_draft(peer: String) {
    if let Ok(rt) = runtime().try_read() {
        rt.abandon_draft(&peer);
    }
}

/// Tell every comrade, once, that this person might need them — the deliberate
/// trigger behind the breathing screen.
///
/// What this discloses, stated plainly: each comrade — nobody else, and no
/// relay — is told that you might need them, and *nothing else*. It is the same
/// envelope an abandoned draft sends, so they cannot tell which happened, and
/// it shares that trigger's cooldown so the two can never add up to two
/// notifications. Nothing is stored locally about having done it.
///
/// Returns how many nudges a relay accepted; `0` when no comrades are chosen.
/// Never fails — like presence, this is a courtesy.
pub async fn nudge_comrades() -> u64 {
    let handles = runtime().read().await.handles();
    handles.nudge_comrades().await
}

// ── Journal (strictly local) ─────────────────────────────────────────────────

pub fn add_journal_entry(text: String, mood: Option<String>) -> Result<JournalEntryDto, UiError> {
    runtime()
        .blocking_read()
        .add_journal_entry(&text, mood.as_deref())
}

/// Save a journal entry that is a recording — a voice entry or a video entry the
/// frontend has already written to its own directory for that kind. The core
/// never opens, moves or deletes that file — see `JournalRecordingDto` for the
/// split and what it costs. `recording.mime` is what picks the player, and it
/// may not be blank.
pub fn add_journal_recording(
    title: Option<String>,
    text: String,
    mood: Option<String>,
    recording: JournalRecordingDto,
) -> Result<JournalEntryDto, UiError> {
    runtime().blocking_read().add_journal_recording(
        title.as_deref(),
        &text,
        mood.as_deref(),
        recording,
    )
}

/// Rename an entry, or clear the title with `None`. `None` back means no entry
/// has that id. Only the title changes — not the words, the mood, the recording
/// or when it was written.
pub fn set_journal_entry_title(
    id: String,
    title: Option<String>,
) -> Result<Option<JournalEntryDto>, UiError> {
    runtime()
        .blocking_read()
        .set_journal_entry_title(&id, title.as_deref())
}

pub fn journal_entries() -> Result<Vec<JournalEntryDto>, UiError> {
    runtime().blocking_read().journal_entries()
}

/// Remove an entry. For a recording entry this removes the record only: the file is
/// the frontend's and the frontend must delete it too.
pub fn delete_journal_entry(id: String) -> Result<bool, UiError> {
    runtime().blocking_read().delete_journal_entry(&id)
}

/// Hand one journal entry to one peer, as an ordinary DM. A copy: the entry is
/// not marked, moved or changed — see `RuntimeHandles::share_journal_entry`.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn share_journal_entry(peer: String, entry_id: String) -> Result<MessageDto, UiError> {
    let handles = runtime().read().await.handles();
    handles.share_journal_entry(&peer, &entry_id).await
}

// ── Tara (reflective companion — strictly local, not therapy) ────────────────

/// Persist the user's message, compute Tara's on-device reply, persist and
/// return it. `crisis == true` on the reply means the UI must surface
/// [`tara_crisis_resources`] with it.
pub fn tara_send(text: String) -> Result<TaraMessageDto, UiError> {
    runtime().blocking_read().tara_send(&text)
}

/// The whole Tara thread, oldest-first (chat order).
pub fn tara_thread() -> Result<Vec<TaraMessageDto>, UiError> {
    runtime().blocking_read().tara_thread()
}

/// Delete the entire Tara thread; returns how many turns were removed.
pub fn clear_tara_thread() -> Result<u64, UiError> {
    runtime().blocking_read().clear_tara_thread()
}

/// The opener shown while the thread is empty — shaped by recent journal mood
/// markers only, never entry text.
pub fn tara_opener() -> Result<String, UiError> {
    runtime().blocking_read().tara_opener()
}

/// The crisis helplines Tara hands off to.
pub fn tara_crisis_resources() -> Vec<CrisisResourceDto> {
    runtime().blocking_read().tara_crisis_resources()
}

// ── Calls (voice/video signaling) ────────────────────────────────────────────

pub fn call_ice_servers() -> Vec<IceServerDto> {
    runtime().blocking_read().call_ice_servers()
}

pub fn call_ice_servers_for(strategy: IceStrategy) -> Vec<IceServerDto> {
    runtime()
        .blocking_read()
        .call_ice_servers_for(strategy.as_str())
}

/// The 4-emoji short authentication string (SAS) for the in-progress call
/// whose local/remote SDPs are `local_sdp`/`remote_sdp`. `None` when either
/// side's SDP carries no `a=fingerprint:` line to derive a code from.
pub fn call_sas(local_sdp: String, remote_sdp: String) -> Option<Vec<String>> {
    runtime().blocking_read().call_sas(&local_sdp, &remote_sdp)
}

pub fn set_turn_server(url: String, username: String, credential: String) -> Result<(), UiError> {
    runtime()
        .blocking_read()
        .set_turn_server(&url, &username, &credential)
}

/// The "is a relay configured" diagnostic status. Carries the URL only; never
/// the username/credential.
pub fn turn_server_status() -> TurnServerStatusDto {
    runtime().blocking_read().turn_server_status()
}

pub fn place_call(peer: String, media: CallMediaKind) -> Result<CallSessionDto, UiError> {
    runtime().blocking_read().place_call(&peer, media.as_str())
}

/// `signal` crosses as the real [`CallSignal`] enum, not a JSON blob — only
/// this crate still round-trips it through JSON internally, since that's the
/// wire format the encrypted DM channel carries.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn send_call_signal(
    peer: String,
    call_id: String,
    media: CallMediaKind,
    signal: CallSignal,
) -> Result<(), UiError> {
    let signal_json = serde_json::to_string(&signal).map_err(|e| UiError::Engine(e.to_string()))?;
    let handles = runtime().read().await.handles();
    handles
        .send_call_signal(&peer, &call_id, media.as_str(), &signal_json)
        .await
}

/// Classify the ICE candidate pair a transfer connection selected.
pub fn share_classify_path(local_type: String, remote_type: String) -> IcePathKind {
    IcePathKind::classify(&local_type, &remote_type)
}

/// Whether a transfer over `path` may proceed under `policy` — see the uniffi twin.
///
/// `consent_granted` answers a question a previous call asked by returning
/// `NeedsConsent`. It can only turn that into `Allow`; a refusal stays refused
/// however insistently a frontend claims consent.
pub fn share_transfer_verdict(
    path: IcePathKind,
    total_bytes: u64,
    policy: RelayPolicy,
    consent_granted: bool,
) -> TransferVerdict {
    comrade_core::share::transport::decide_with_consent(path, total_bytes, policy, consent_granted)
}

/// Whether a transfer connection built under `policy` may be offered TURN.
pub fn share_ice_servers_allowed(policy: RelayPolicy) -> bool {
    comrade_core::share::transport::ice_servers_allowed(policy)
}

/// Recognise a Spotify / Apple Music / YouTube link. Pure and offline.
pub fn parse_music_link(input: String) -> Option<MusicLink> {
    comrade_core::together::parse_music_link(&input)
}

/// Score a library candidate against what the peer named — see the uniffi twin.
pub fn together_match_score(want: Recording, have: Recording, want_ms: u64, have_ms: u64) -> f64 {
    comrade_core::together::match_score(&want, &have, want_ms, have_ms)
}

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn together_start(
    peer: String,
    content: TogetherContent,
) -> Result<TogetherSessionDto, UiError> {
    let handles = runtime().read().await.handles();
    handles.together_start(&peer, content).await
}

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn together_join() -> Result<(), UiError> {
    let handles = runtime().read().await.handles();
    handles.together_join().await
}

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn together_set_state(
    pos_ms: u64,
    playing: bool,
    effective_in_ms: u64,
) -> Result<(), UiError> {
    let handles = runtime().read().await.handles();
    handles
        .together_set_state(pos_ms, playing, effective_in_ms)
        .await
}

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn together_end() -> Result<(), UiError> {
    let handles = runtime().read().await.handles();
    handles.together_end().await
}

/// Report where our own player is. Synchronous and skipped under contention —
/// see [`Comrade::together_report_position`] in this crate's uniffi half.
pub fn together_report_position(pos_ms: u64, playing: bool, output_latency_ms: u64) {
    if let Ok(rt) = runtime().try_read() {
        rt.together_report_position(pos_ms, playing, output_latency_ms);
    }
}

/// Declare whether a direct peer channel is carrying this session — see
/// [`Comrade::together_direct_ready`] in this crate's uniffi half.
pub fn together_direct_ready(ready: bool) {
    if let Ok(rt) = runtime().try_read() {
        rt.together_direct_ready(ready);
    }
}

/// Hand over an envelope that arrived on the direct channel — see
/// [`Comrade::together_receive_direct`] in this crate's uniffi half.
pub fn together_receive_direct(json: String) {
    if let Ok(rt) = runtime().try_read() {
        rt.together_receive_direct(&json);
    }
}

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn hangup_call(
    peer: String,
    call_id: String,
    media: CallMediaKind,
    reason: HangupReason,
) -> Result<(), UiError> {
    let handles = runtime().read().await.handles();
    handles
        .hangup_call(&peer, &call_id, media.as_str(), reason.as_str())
        .await
}

#[allow(clippy::too_many_arguments)]
pub fn log_call(
    peer: String,
    call_id: String,
    media: CallMediaKind,
    incoming: bool,
    outcome: String,
    started_at: u64,
    duration_secs: u64,
) -> Result<CallRecordDto, UiError> {
    runtime().blocking_read().log_call(
        &peer,
        &call_id,
        media.as_str(),
        incoming,
        &outcome,
        started_at,
        duration_secs,
    )
}

pub fn call_history(peer: Option<String>) -> Result<Vec<CallRecordDto>, UiError> {
    runtime().blocking_read().call_history(peer.as_deref())
}

// ── Encrypted media (NIP-94/96 · Blossom) ────────────────────────────────────

/// `bytes` crosses as a native byte array.
///
/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn upload_and_send_media(
    target_pubkey: String,
    bytes: Vec<u8>,
    mime_type: String,
    caption: String,
) -> Result<MediaMessageDto, UiError> {
    let handles = runtime().read().await.handles();
    handles
        .upload_and_send_media(&target_pubkey, bytes, &mime_type, &caption)
        .await
}

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn download_and_decrypt_media(event_id: String) -> Result<MediaBytesDto, UiError> {
    let handles = runtime().read().await.handles();
    handles.download_and_decrypt_media(&event_id).await
}

// ── Sakha/Sakhi CRDT ledger ──────────────────────────────────────────────────

/// See [`broadcast_chitthi`] for the lock discipline.
pub async fn sync_ledger() -> Result<String, UiError> {
    let handles = runtime().read().await.handles();
    handles.sync_ledger().await
}

// ── Push events ──────────────────────────────────────────────────────────────

/// Every [`BridgeEvent`], as a Dart `Stream`.
///
/// The Dart counterpart of `Comrade::set_event_listener`, and deliberately
/// sourced from the *same* two `tokio::sync::broadcast` channels the uniffi
/// listener forwards — `broadcast` fans out to every receiver, so a Kotlin
/// service listening through uniffi and a Flutter UI listening through this
/// stream both see every event, simultaneously, with neither starving the
/// other.
///
/// Two channels are merged, exactly as `set_event_listener` forwards two:
/// the critical stream (DMs, requests, call signals, mesh/ledger updates) and
/// the separate, small, deliberately-lossy `IncomingChitthi` feed stream (see
/// `comrade_ui::ComradeRuntime::subscribe_feed_events`, AUDIT.md COMMS-04), so
/// a public-feed flood can never delay a call signal queued behind it.
///
/// Subscribing late is safe but not retroactive: `broadcast` receivers only
/// see events sent after they subscribe, so call this before [`unlock_vault`].
/// Dropping the Dart subscription ends the task.
pub async fn bridge_event_stream(sink: StreamSink<BridgeEvent>) {
    let (critical_rx, feed_rx) = {
        let guard = runtime().read().await;
        (guard.subscribe_events(), guard.subscribe_feed_events())
    };
    // `sink.add` returns `Err` once Dart has dropped the subscription.
    pump_bridge_events(critical_rx, feed_rx, |event| sink.add(event).is_ok()).await
}

/// The fan-in half of [`bridge_event_stream`], with the Dart sink replaced by
/// `emit` (returning `false` when the consumer is gone).
///
/// Split out purely so it can be tested: a real `StreamSink` needs a live Dart
/// isolate port to construct, which no Rust test can provide. `pub(crate)`, so
/// FRB's parser leaves it alone — only `pub` items in this module become Dart
/// functions.
pub(crate) async fn pump_bridge_events<F>(
    mut critical_rx: tokio::sync::broadcast::Receiver<BridgeEvent>,
    mut feed_rx: tokio::sync::broadcast::Receiver<BridgeEvent>,
    mut emit: F,
) where
    F: FnMut(BridgeEvent) -> bool,
{
    // `broadcast::Receiver::recv` is cancel-safe, so `select!` dropping the
    // loser's future each iteration cannot lose an event on that channel.
    //
    // `Lagged` means this receiver fell behind *that channel's own* ring
    // buffer — never a cross-channel effect, since the two have independent
    // buffers. Log the skip count and keep going rather than tear the stream
    // down; `Closed` only happens when the runtime itself is going away.
    loop {
        let event = tokio::select! {
            r = critical_rx.recv() => r,
            r = feed_rx.recv() => r,
        };
        match event {
            Ok(event) => {
                if !emit(event) {
                    break;
                }
            }
            Err(tokio::sync::broadcast::error::RecvError::Lagged(skipped)) => {
                tracing::warn!(
                    skipped,
                    "Dart event stream fell behind a broadcast channel's capacity; \
                     some events were skipped"
                );
            }
            Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
        }
    }
}
