/*!
 * comrade_jni — the Android FFI boundary, generated by uniffi-rs.
 *
 * This crate used to hand-write one `#[no_mangle] pub extern "C" fn
 * Java_mullu_comrade_ComradeCore_<name>` per operation, marshal every argument
 * and return value through `serde_json`, and catch panics with a bespoke
 * `guard_json` helper (see git history). All of that is now generated:
 * `uniffi::setup_scaffolding!` below emits the `extern "C"` layer, and
 * [`Comrade`]'s exported methods are lowered/lifted directly — no JSON, no
 * manual panic guard (uniffi's scaffolding catches panics itself and turns
 * them into a `PanicException` on the Kotlin side).
 *
 * Shape:
 *  • Free functions ([`version`], [`generate_keypair`], …) — stateless crypto
 *    and workspace-metadata helpers that don't need a live runtime.
 *  • [`Comrade`] — an opaque uniffi `Object` (handed to Kotlin as a single
 *    `Comrade()` instance, constructed once and reused — the same
 *    "one shared instance for the process" shape as the desktop's
 *    `Arc<RwLock<ComradeRuntime>>` managed state) wrapping every
 *    [`comrade_ui::ComradeRuntime`] method the Vault (DMs/calls/media),
 *    Sabha (public feed) and Identity (profile/contacts/workspace) engines
 *    expose. Methods that only read/write `ComradeRuntime`'s own fields stay
 *    synchronous (`.blocking_read()`/`.blocking_write()`); methods whose call
 *    path needs a live Tokio reactor (a relay round-trip, or a fire-and-forget
 *    `tokio::spawn` receipt/profile-share deep inside `comrade_ui`) are
 *    `async fn` under `#[uniffi::export(async_runtime = "tokio")]`, which
 *    Kotlin sees as a `suspend fun` and which `async-compat` drives on a
 *    runtime of its own — no process-global `tokio::runtime::Runtime` to
 *    manage by hand any more.
 *  • [`BridgeEventListener`] — a uniffi callback interface Kotlin implements
 *    to receive [`BridgeEvent`]s pushed live, replacing the old `pollEvent()`
 *    JNI call that Kotlin had to re-invoke on a 600ms timer.
 */

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use comrade_core::call::{CallMediaKind, CallSignal, HangupReason, IceStrategy};
use comrade_core::crypto::KeyProfile;
use comrade_state::AppWorkspace;
use comrade_ui::{
    BridgeEvent, CallRecordDto, CallSessionDto, ChitthiDto, ComradeRuntime, ContactDto,
    ConversationDto, FoundProfileDto, IceServerDto, IdentityDto, JournalEntryDto, MediaBytesDto,
    MediaMessageDto, MeshStatusDto, MessageDto, MessageRequestDto, ProfileDto, TurnServerStatusDto,
    UiError, UpiIntentDto, WorkspaceDto,
};
use tokio::sync::RwLock;

uniffi::setup_scaffolding!("comrade");

// ── Stateless helpers (no ComradeRuntime instance needed) ────────────────────

/// The comrade_jni crate version (e.g. "0.1.0").
#[uniffi::export]
pub fn version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

/// A freshly generated secp256k1 keypair, Bech32-encoded. Standalone —
/// doesn't touch the encrypted store; see [`Comrade::generate_identity`] and
/// [`Comrade::unlock_vault`] for the store-backed identity flow every UI
/// screen actually drives.
#[derive(uniffi::Record)]
pub struct KeypairDto {
    pub npub: String,
    pub nsec: String,
}

#[uniffi::export]
pub fn generate_keypair() -> Result<KeypairDto, UiError> {
    let profile = KeyProfile::generate().map_err(|e| UiError::Crypto(e.to_string()))?;
    Ok(KeypairDto {
        npub: profile.npub,
        nsec: profile.nsec,
    })
}

/// Derive the npub from an nsec Bech32 string, or `None` if it doesn't parse.
#[uniffi::export]
pub fn npub_from_nsec(nsec: String) -> Option<String> {
    KeyProfile::from_nsec(&nsec).ok().map(|p| p.npub)
}

/// The display label for a workspace discriminant (`"Base"`,
/// `"OffGridTravel"`, `"CoupleSandboxSakha"`, `"CoupleSandboxSakhi"`), or
/// `None` for an unknown key.
#[uniffi::export]
pub fn workspace_label(workspace: String) -> Option<String> {
    AppWorkspace::from_key(&workspace).map(|ws| ws.label().to_string())
}

/// A workspace discriminant paired with its display label.
#[derive(uniffi::Record)]
pub struct WorkspaceKeyLabel {
    pub key: String,
    pub label: String,
}

/// Every workspace discriminant and its label — a stable, store-free list
/// (contrast [`Comrade::workspaces`], which also reports which one is active).
#[uniffi::export]
pub fn all_workspaces() -> Vec<WorkspaceKeyLabel> {
    AppWorkspace::all()
        .iter()
        .map(|ws| WorkspaceKeyLabel {
            key: ws.key().to_string(),
            label: ws.label().to_string(),
        })
        .collect()
}

// ── Push events ───────────────────────────────────────────────────────────────

/// Implemented in Kotlin to receive [`BridgeEvent`]s as they happen. Register
/// with [`Comrade::set_event_listener`] — ideally right after constructing
/// [`Comrade`] and before [`Comrade::unlock_vault`], so no event emitted by
/// the background feed/DM loops arrives before anyone is listening.
#[uniffi::export(foreign)]
pub trait BridgeEventListener: Send + Sync {
    fn on_event(&self, event: BridgeEvent);
}

/// Drain one `BridgeEvent` channel to `listener` until it closes. A `Lagged`
/// error means this receiver fell behind that channel's own capacity and
/// some events on *that* channel were skipped — never a cross-channel
/// effect, since each of the two channels `set_event_listener` forwards has
/// its own independent ring buffer.
fn spawn_event_forwarder(
    mut rx: tokio::sync::broadcast::Receiver<BridgeEvent>,
    listener: Arc<dyn BridgeEventListener>,
) {
    tokio::spawn(async move {
        loop {
            match rx.recv().await {
                Ok(event) => listener.on_event(event),
                Err(tokio::sync::broadcast::error::RecvError::Lagged(_)) => continue,
                Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
            }
        }
    });
}

// ── Comrade — the live runtime handle ────────────────────────────────────────

/// The single, process-lifetime handle to the native core. Kotlin constructs
/// this exactly once (mirroring the desktop's `Arc<RwLock<ComradeRuntime>>`
/// managed state) and calls every method on that one instance — uniffi hands
/// it to Kotlin as `Arc<Comrade>` under the hood, so cloning the reference is
/// cheap and every method call is thread-safe.
#[derive(uniffi::Object)]
pub struct Comrade {
    inner: RwLock<ComradeRuntime>,
    listener_registered: AtomicBool,
}

#[uniffi::export(async_runtime = "tokio")]
impl Comrade {
    #[uniffi::constructor]
    pub fn new() -> Arc<Self> {
        Arc::new(Self {
            inner: RwLock::new(ComradeRuntime::new()),
            listener_registered: AtomicBool::new(false),
        })
    }

    /// Like [`Comrade::new`], but connecting new engines to `relays` instead
    /// of the public default set. AUDIT.md COMMS-03's isolated-relay test
    /// hook: a two-installation/two-instance device test points both sides
    /// at one local relay instead of the public internet. Not used by the
    /// shipping app (which always calls [`Comrade::new`]).
    #[uniffi::constructor]
    pub fn new_with_relays(relays: Vec<String>) -> Arc<Self> {
        Arc::new(Self {
            inner: RwLock::new(ComradeRuntime::with_relays(relays)),
            listener_registered: AtomicBool::new(false),
        })
    }

    // ── Push events ───────────────────────────────────────────────────────

    /// Register `listener` to receive every future [`BridgeEvent`]. Only the
    /// first call takes effect (idempotent, like [`Comrade::unlock_vault`]) —
    /// the app registers one listener for its lifetime.
    ///
    /// Forwards *two* independent channels to the same `listener` — the
    /// critical stream (DMs, requests, call signals, terminal call events,
    /// mesh/ledger updates) and the separate, small, deliberately-lossy
    /// `IncomingChitthi` stream (see `comrade_ui::ComradeRuntime::subscribe_feed_events`,
    /// AUDIT.md COMMS-04) — so a public-feed flood dropping old, unconsumed
    /// Chitthis on its own channel can never delay or starve a call
    /// signal/DM/request queued behind it on the critical one.
    pub async fn set_event_listener(&self, listener: Arc<dyn BridgeEventListener>) {
        if self.listener_registered.swap(true, Ordering::SeqCst) {
            return;
        }
        let guard = self.inner.read().await;
        let critical_rx = guard.subscribe_events();
        let feed_rx = guard.subscribe_feed_events();
        drop(guard);
        spawn_event_forwarder(critical_rx, listener.clone());
        spawn_event_forwarder(feed_rx, listener);
    }

    // ── Vault unlock / lifecycle ────────────────────────────────────────────

    /// Open the encrypted store, restore or seed the identity, build the
    /// engines, and start the background feed/DM loops. Safe to call more
    /// than once (returns the already-loaded identity).
    pub async fn unlock_vault(
        &self,
        path: String,
        passphrase: String,
    ) -> Result<IdentityDto, UiError> {
        let mut guard = self.inner.write().await;
        let identity = guard.unlock_vault(&path, &passphrase).await?;
        guard.spawn_event_loops();
        Ok(identity)
    }

    pub fn is_vault_unlocked(&self) -> bool {
        self.inner.blocking_read().is_vault_unlocked()
    }

    pub fn is_store_unlocked(&self) -> bool {
        self.inner.blocking_read().is_store_unlocked()
    }

    /// Re-lock the vault: abort the background feed/DM/sakha loops and drop
    /// the store, engines, and in-memory identity — see
    /// `comrade_ui::ComradeRuntime::lock_vault`. Async because stopping a
    /// live Saathi mesh engine (if the workspace has one running) awaits its
    /// shutdown; every other step is synchronous state teardown.
    pub async fn lock_vault(&self) {
        self.inner.write().await.lock_vault().await
    }

    // ── Identity ────────────────────────────────────────────────────────────

    pub fn generate_identity(&self) -> Result<IdentityDto, UiError> {
        self.inner.blocking_write().generate_identity()
    }

    pub fn current_identity(&self) -> Option<IdentityDto> {
        self.inner.blocking_read().current_identity()
    }

    pub fn extract_payments(&self, text: String) -> Result<Vec<UpiIntentDto>, UiError> {
        self.inner.blocking_read().extract_payments(&text)
    }

    // ── Workspace controller ────────────────────────────────────────────────

    pub fn workspaces(&self) -> Vec<WorkspaceDto> {
        self.inner.blocking_read().workspaces()
    }

    pub fn current_workspace(&self) -> WorkspaceDto {
        self.inner.blocking_read().current_workspace()
    }

    /// Async (not because a reactor is strictly needed for the workspace
    /// switch itself, but because it now also starts/stops the Saathi mesh
    /// engine to match — see `comrade_ui::ComradeRuntime::toggle_workspace`).
    pub async fn toggle_workspace(&self, target: String) -> Result<WorkspaceDto, UiError> {
        self.inner.write().await.toggle_workspace(&target).await
    }

    /// Async for the same reason as [`Comrade::toggle_workspace`].
    pub async fn back(&self) -> WorkspaceDto {
        self.inner.write().await.back().await
    }

    /// Snapshot of the off-grid Saathi mesh's live status (mDNS discovery +
    /// Gossipsub) — for seeding a UI's connectivity indicator before the
    /// first [`BridgeEvent::MeshStatusChanged`] arrives. Never fails: the
    /// mesh being off is a valid, common state, not an error.
    pub fn mesh_status(&self) -> MeshStatusDto {
        self.inner.blocking_read().mesh_status()
    }

    // ── Sabha (public feed) ─────────────────────────────────────────────────

    pub fn fetch_sabha_timeline(&self) -> Result<Vec<ChitthiDto>, UiError> {
        self.inner.blocking_read().fetch_sabha_timeline()
    }

    pub async fn broadcast_chitthi(
        &self,
        content: String,
        reply_to: Option<String>,
    ) -> Result<String, UiError> {
        self.inner
            .read()
            .await
            .broadcast_chitthi(&content, reply_to)
            .await
    }

    // ── Vault (E2E DMs) ──────────────────────────────────────────────────────

    pub async fn send_dm(&self, target: String, content: String) -> Result<MessageDto, UiError> {
        self.inner.read().await.send_dm(&target, &content).await
    }

    pub async fn send_dm_reply(
        &self,
        target: String,
        content: String,
        reply_to: Option<String>,
    ) -> Result<MessageDto, UiError> {
        self.inner
            .read()
            .await
            .send_dm_reply(&target, &content, reply_to.as_deref())
            .await
    }

    pub fn conversations(&self) -> Result<Vec<ConversationDto>, UiError> {
        self.inner.blocking_read().conversations()
    }

    pub fn messages_with(&self, peer: String) -> Result<Vec<MessageDto>, UiError> {
        self.inner.blocking_read().messages_with(&peer)
    }

    /// Full encrypted-media history with `peer`, oldest first — the media
    /// counterpart of [`Comrade::messages_with`], for rendering past
    /// attachments inline after a restart, not just ones received live.
    pub fn media_with(&self, peer: String) -> Result<Vec<MediaMessageDto>, UiError> {
        self.inner.blocking_read().media_with(&peer)
    }

    // ── Message requests (stranger gating) + receipts ──────────────────────

    pub fn message_requests(&self) -> Result<Vec<MessageRequestDto>, UiError> {
        self.inner.blocking_read().message_requests()
    }

    /// Async (not because the underlying call is itself `async fn`, but
    /// because accepting a request fires a background profile-share + receipt
    /// send that needs a live reactor to `tokio::spawn` onto — see
    /// `comrade_ui::ComradeRuntime::accept_request`).
    pub async fn accept_request(&self, peer: String) -> Result<(), UiError> {
        self.inner.read().await.accept_request(&peer)
    }

    pub fn block_conversation(&self, peer: String) -> Result<(), UiError> {
        self.inner.blocking_read().block_conversation(&peer)
    }

    /// Async for the same reason as [`Comrade::accept_request`] — the
    /// read-receipt send is a background `tokio::spawn`.
    pub async fn mark_conversation_read(&self, peer: String) -> Result<(), UiError> {
        self.inner.read().await.mark_conversation_read(&peer)
    }

    // ── Profile & contacts ──────────────────────────────────────────────────

    pub fn profile(&self) -> Result<ProfileDto, UiError> {
        self.inner.blocking_read().profile()
    }

    pub async fn set_username(&self, name: String) -> Result<ProfileDto, UiError> {
        self.inner.write().await.set_username(&name).await
    }

    pub fn add_contact(&self, npub: String, alias: String) -> Result<ContactDto, UiError> {
        self.inner.blocking_read().add_contact(&npub, &alias)
    }

    pub fn set_contact_alias(&self, npub: String, alias: String) -> Result<ContactDto, UiError> {
        self.inner.blocking_read().set_contact_alias(&npub, &alias)
    }

    pub fn remove_contact(&self, npub: String) -> Result<bool, UiError> {
        self.inner.blocking_read().remove_contact(&npub)
    }

    pub fn list_contacts(&self) -> Result<Vec<ContactDto>, UiError> {
        self.inner.blocking_read().list_contacts()
    }

    pub async fn search_profiles(&self, query: String) -> Result<Vec<FoundProfileDto>, UiError> {
        self.inner.read().await.search_profiles(&query).await
    }

    /// Detaches the refresher and drops the shared lock before the relay
    /// round-trip (AUDIT P2: never hold the runtime lock across a network
    /// await), matching `comrade_ui::ComradeRuntime::refresh_peer_profiles`.
    pub async fn refresh_peer_profiles(&self) -> Result<u64, UiError> {
        let refresher = self.inner.read().await.profile_refresher()?;
        let changed = refresher.run().await?;
        Ok(changed as u64)
    }

    // ── Journal (strictly local) ─────────────────────────────────────────────

    pub fn add_journal_entry(
        &self,
        text: String,
        mood: Option<String>,
    ) -> Result<JournalEntryDto, UiError> {
        self.inner
            .blocking_read()
            .add_journal_entry(&text, mood.as_deref())
    }

    pub fn journal_entries(&self) -> Result<Vec<JournalEntryDto>, UiError> {
        self.inner.blocking_read().journal_entries()
    }

    pub fn delete_journal_entry(&self, id: String) -> Result<bool, UiError> {
        self.inner.blocking_read().delete_journal_entry(&id)
    }

    // ── Calls (voice/video signaling) ───────────────────────────────────────

    pub fn call_ice_servers(&self) -> Vec<IceServerDto> {
        self.inner.blocking_read().call_ice_servers()
    }

    pub fn call_ice_servers_for(&self, strategy: IceStrategy) -> Vec<IceServerDto> {
        self.inner
            .blocking_read()
            .call_ice_servers_for(strategy.as_str())
    }

    /// The 4-emoji short authentication string (SAS) for the in-progress call
    /// whose local/remote SDPs are `local_sdp`/`remote_sdp` — see
    /// `comrade_ui::ComradeRuntime::call_sas`. `None` when either side's SDP
    /// carries no `a=fingerprint:` line to derive a code from.
    pub fn call_sas(&self, local_sdp: String, remote_sdp: String) -> Option<Vec<String>> {
        self.inner.blocking_read().call_sas(&local_sdp, &remote_sdp)
    }

    pub fn set_turn_server(
        &self,
        url: String,
        username: String,
        credential: String,
    ) -> Result<(), UiError> {
        self.inner
            .blocking_read()
            .set_turn_server(&url, &username, &credential)
    }

    /// The "is a relay configured" diagnostic status — see
    /// `comrade_ui::ComradeRuntime::turn_server_status`. Carries the URL only;
    /// never the username/credential.
    pub fn turn_server_status(&self) -> TurnServerStatusDto {
        self.inner.blocking_read().turn_server_status()
    }

    pub fn place_call(
        &self,
        peer: String,
        media: CallMediaKind,
    ) -> Result<CallSessionDto, UiError> {
        self.inner.blocking_read().place_call(&peer, media.as_str())
    }

    /// `signal` crosses as the real [`CallSignal`] enum, not a JSON blob —
    /// only this crate still round-trips it through JSON internally, since
    /// that's the wire format `comrade_ui::ComradeRuntime::send_call_signal`
    /// puts on the encrypted DM channel.
    pub async fn send_call_signal(
        &self,
        peer: String,
        call_id: String,
        media: CallMediaKind,
        signal: CallSignal,
    ) -> Result<(), UiError> {
        let signal_json =
            serde_json::to_string(&signal).map_err(|e| UiError::Engine(e.to_string()))?;
        self.inner
            .read()
            .await
            .send_call_signal(&peer, &call_id, media.as_str(), &signal_json)
            .await
    }

    pub async fn hangup_call(
        &self,
        peer: String,
        call_id: String,
        media: CallMediaKind,
        reason: HangupReason,
    ) -> Result<(), UiError> {
        self.inner
            .read()
            .await
            .hangup_call(&peer, &call_id, media.as_str(), reason.as_str())
            .await
    }

    #[allow(clippy::too_many_arguments)]
    pub fn log_call(
        &self,
        peer: String,
        call_id: String,
        media: CallMediaKind,
        incoming: bool,
        outcome: String,
        started_at: u64,
        duration_secs: u64,
    ) -> Result<CallRecordDto, UiError> {
        self.inner.blocking_read().log_call(
            &peer,
            &call_id,
            media.as_str(),
            incoming,
            &outcome,
            started_at,
            duration_secs,
        )
    }

    pub fn call_history(&self, peer: Option<String>) -> Result<Vec<CallRecordDto>, UiError> {
        self.inner.blocking_read().call_history(peer.as_deref())
    }

    // ── Encrypted media (NIP-94/96 · Blossom) ───────────────────────────────

    /// `bytes` crosses as a native byte array — uniffi handles `Vec<u8>`
    /// directly, so the base64 encode/decode the old JNI bridge needed
    /// (Kotlin `String` was the only wire type available) is gone.
    pub async fn upload_and_send_media(
        &self,
        target_pubkey: String,
        bytes: Vec<u8>,
        mime_type: String,
        caption: String,
    ) -> Result<MediaMessageDto, UiError> {
        self.inner
            .read()
            .await
            .upload_and_send_media(&target_pubkey, bytes, &mime_type, &caption)
            .await
    }

    pub async fn download_and_decrypt_media(
        &self,
        event_id: String,
    ) -> Result<MediaBytesDto, UiError> {
        self.inner
            .read()
            .await
            .download_and_decrypt_media(&event_id)
            .await
    }

    // ── Sakha/Sakhi CRDT ledger ──────────────────────────────────────────────

    pub async fn sync_ledger(&self) -> Result<String, UiError> {
        self.inner.read().await.sync_ledger().await
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────
//
// The generated `extern "C"` scaffolding needs a foreign runtime (Kotlin/JNA)
// to exercise, but every function/method above is still plain Rust under
// that scaffolding — test it directly, the same way `comrade_ui`'s own tests
// drive `ComradeRuntime` without a JNI/Tauri host in the loop.

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_matches_crate_version() {
        assert_eq!(version(), env!("CARGO_PKG_VERSION"));
    }

    #[test]
    fn generate_keypair_produces_valid_bech32() {
        let kp = generate_keypair().expect("keygen must not fail");
        assert!(kp.npub.starts_with("npub1"));
        assert!(kp.nsec.starts_with("nsec1"));
    }

    #[test]
    fn npub_from_nsec_round_trips_and_rejects_garbage() {
        let kp = generate_keypair().unwrap();
        assert_eq!(npub_from_nsec(kp.nsec), Some(kp.npub));
        assert_eq!(npub_from_nsec("not an nsec".to_string()), None);
    }

    #[test]
    fn workspace_label_known_and_unknown_keys() {
        assert!(workspace_label("Base".to_string()).is_some());
        assert_eq!(workspace_label("NotAWorkspace".to_string()), None);
    }

    #[test]
    fn all_workspaces_lists_every_workspace_with_labels() {
        let list = all_workspaces();
        assert_eq!(list.len(), AppWorkspace::all().len());
        assert!(list.iter().any(|w| w.key == "Base"));
        for w in &list {
            assert!(!w.key.is_empty());
            assert!(!w.label.is_empty());
        }
    }

    // Plain (non-async) `#[test]`s for the sync tier — these must run with NO
    // ambient Tokio runtime, exactly like a real call from a JNA/native
    // thread: `blocking_read`/`blocking_write` panic if called from inside
    // one (see `tokio::sync::RwLock::blocking_read` docs), so exercising them
    // under `#[tokio::test]` would fail for a reason that says nothing about
    // this crate's own correctness.

    #[test]
    fn comrade_starts_locked_on_the_base_workspace() {
        let c = Comrade::new();
        assert!(!c.is_vault_unlocked());
        assert!(!c.is_store_unlocked());
        assert_eq!(c.current_workspace().key, "Base");
    }

    #[test]
    fn new_with_relays_is_reachable_through_the_ffi_constructor() {
        let c = Comrade::new_with_relays(vec!["wss://relay.example.test".to_string()]);
        assert!(!c.is_vault_unlocked());
        assert_eq!(c.current_workspace().key, "Base");
    }

    #[test]
    fn sync_calls_reject_gracefully_before_unlock() {
        // Mirrors comrade_ui::runtime::tests::commands_reject_gracefully_when_vault_locked
        // — this wrapper must not panic or silently succeed pre-unlock.
        let c = Comrade::new();
        assert!(matches!(c.conversations(), Err(UiError::VaultLocked)));
        assert!(matches!(c.profile(), Err(UiError::NoIdentity)));
    }

    #[test]
    fn call_sas_needs_no_unlock_and_is_order_independent() {
        // Pure computation over the two SDP strings already in hand — unlike
        // the store-backed calls above, this must work before the vault is
        // ever unlocked.
        let c = Comrade::new();
        let sdp_a = "v=0\r\na=fingerprint:sha-256 AA:BB\r\n".to_string();
        let sdp_b = "v=0\r\na=fingerprint:sha-256 CC:DD\r\n".to_string();
        let sas = c.call_sas(sdp_a.clone(), sdp_b.clone());
        assert_eq!(sas.as_ref().map(Vec::len), Some(4));
        assert_eq!(sas, c.call_sas(sdp_b, sdp_a));
    }

    // `#[tokio::test]` for the async tier — these run under
    // `async_runtime = "tokio"`'s real calling convention (an active
    // reactor), same as the sync tests above run under none.

    #[tokio::test]
    async fn async_calls_reject_gracefully_before_unlock() {
        let c = Comrade::new();
        assert!(matches!(
            c.send_call_signal(
                "peer".to_string(),
                "call1".to_string(),
                CallMediaKind::Audio,
                CallSignal::Ringing,
            )
            .await,
            Err(UiError::VaultLocked)
        ));
    }

    #[test]
    fn lock_vault_is_reachable_through_the_ffi_object_and_is_idempotent() {
        // A plain (non-async) `#[test]`, like `comrade_starts_locked_on_the_base_workspace`
        // above: `is_vault_unlocked`/`profile` go through `blocking_read`, which
        // panics if called from inside an ambient Tokio runtime (i.e. under
        // `#[tokio::test]`) — see that test's doc comment. The async methods
        // (`unlock_vault`/`lock_vault`) instead run on a runtime built and
        // driven by hand via `block_on`, exactly like a real JNA/native caller
        // would (there is no surrounding reactor on that thread either).
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().to_string_lossy().to_string();
        let c = Comrade::new();
        let rt = tokio::runtime::Runtime::new().unwrap();

        rt.block_on(c.unlock_vault(path.clone(), "pin".to_string()))
            .unwrap();
        assert!(c.is_vault_unlocked());

        rt.block_on(c.lock_vault());
        assert!(!c.is_vault_unlocked());
        assert!(matches!(c.profile(), Err(UiError::NoIdentity)));

        // Idempotent — locking an already-locked runtime must not panic.
        rt.block_on(c.lock_vault());
        assert!(!c.is_vault_unlocked());

        // Unlocking again resumes normally.
        rt.block_on(c.unlock_vault(path, "pin".to_string()))
            .unwrap();
        assert!(c.is_vault_unlocked());
    }

    #[test]
    fn turn_server_status_is_reachable_through_the_ffi_object() {
        let c = Comrade::new();
        // Pre-unlock: honest "nothing configured", not an error.
        let status = c.turn_server_status();
        assert!(!status.configured);
        assert_eq!(status.url, None);
    }

    #[tokio::test]
    async fn event_listener_registration_is_idempotent() {
        #[derive(Default)]
        struct Counter(std::sync::atomic::AtomicUsize);
        impl BridgeEventListener for Counter {
            fn on_event(&self, _event: BridgeEvent) {
                self.0.fetch_add(1, Ordering::SeqCst);
            }
        }

        let c = Comrade::new();
        let listener: Arc<dyn BridgeEventListener> = Arc::new(Counter::default());
        c.set_event_listener(listener.clone()).await;
        // A second registration must be a no-op, not a second forwarder task.
        c.set_event_listener(listener).await;
        assert!(c.listener_registered.load(Ordering::SeqCst));
    }
}
