package mullu.comrade

import android.util.Log
import java.util.concurrent.atomic.AtomicBoolean
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.runBlocking
import uniffi.comrade.BridgeEventListener
import uniffi.comrade.Comrade
import uniffi.comrade.allWorkspaces
import uniffi.comrade.generateKeypair
import uniffi.comrade.npubFromNsec
import uniffi.comrade.version
import uniffi.comrade.workspaceLabel as ffiWorkspaceLabel
import uniffi.comrade_core.CallMediaKind
import uniffi.comrade_core.CallSignal
import uniffi.comrade_core.HangupReason
import uniffi.comrade_core.IceStrategy
import uniffi.comrade_ui.BridgeEvent
import uniffi.comrade_ui.UiException

/**
 * Facade over the Rust core, generated by uniffi-rs from crates/comrade_jni.
 *
 * Where a hand-written JNI bridge used to live here — 38 `external fun`
 * declarations, one `guard_json`-wrapped `extern "C"` export apiece in Rust,
 * an `org.json` parse per call on this side — every method below is a thin,
 * typed call into the uniffi-generated [Comrade] object. No JSON crosses the
 * boundary any more; this file's remaining job is to keep the public surface
 * (method names, the `xxxInfo` data classes) that the rest of the app already
 * depends on unchanged, so no UI screen needed to change for the migration.
 *
 * Every method here stays a plain blocking function, exactly like the old
 * JNI calls were — including the roughly dozen operations that are `suspend
 * fun` on [Comrade] itself (uniffi's async export, for calls whose Rust side
 * needs a live Tokio reactor). Each of those is bridged with [runBlocking]
 * rather than becoming `suspend` here, so every existing call site (which
 * already assumes a blocking call and wraps it in `withContext(Dispatchers.IO)`)
 * needs no change. A natural follow-up, once each call site is checked
 * individually, is to make these genuinely `suspend` and drop that manual
 * dispatch — orthogonal to this migration, so left for later.
 *
 * The native library loads lazily on first use of [ffi] — uniffi's generated
 * bindings do this internally (JNA `Native.register`), so there is no
 * `System.loadLibrary` call to make here any more; see [ComradeApplication]
 * for where that first touch is deliberately warmed on a background thread.
 */
object ComradeCore {

    private val ffi: Comrade = Comrade()

    /** Fed by [BridgeEventListener]; drained by [pollEvent]. See [EventBus]. */
    private val eventQueue = EventBus()

    /**
     * Guards [initializeEventBridge] so only the first caller actually
     * registers the FFI listener. `compareAndSet` picks exactly one winner;
     * every other (concurrent or later) caller — e.g. an Activity recreation
     * re-running the same startup path — suspends on [bridgeInitDone] instead
     * of returning early, so nobody observes "initialized" before the
     * registration actually finished (see [initializeEventBridge]).
     */
    private val bridgeInitStarted = AtomicBoolean(false)
    private val bridgeInitDone = CompletableDeferred<Unit>()

    /**
     * Register the native event listener and **await** its registration
     * completing before returning — replacing a `GlobalScope.launch` that
     * used to fire-and-forget this from the class initialiser. That mattered:
     * `GlobalScope.launch` only *schedules* the coroutine, so a caller that
     * touched [ComradeCore] and immediately called [unlockVaultTyped] could
     * race the Rust side actually subscribing to its broadcast channel —
     * `unlockVaultTyped` starts the background feed/DM loops, and any event
     * they publish before a subscriber exists is dropped (a `tokio::sync::
     * broadcast` send with zero receivers is a silent no-op). Callers that
     * need this to have happened before proceeding (see
     * [mullu.comrade.ComradeApplication]) must call this and await it — not
     * rely on class-init timing.
     *
     * Idempotent and race-safe: safe to call from more than one place
     * (application startup *and*, defensively, the first [unlockVaultTyped])
     * without double-registering — and every caller, winner or not, only
     * returns once the real FFI registration has completed, so none of them
     * can race ahead of it.
     */
    suspend fun initializeEventBridge() {
        if (bridgeInitStarted.compareAndSet(false, true)) {
            try {
                ffi.setEventListener(
                    object : BridgeEventListener {
                        override fun onEvent(event: BridgeEvent) {
                            eventQueue.offer(event)
                        }
                    },
                )
                bridgeInitDone.complete(Unit)
            } catch (e: Throwable) {
                // Otherwise every caller waiting on bridgeInitDone below would
                // suspend forever: a Deferred that's never completed (and
                // never failed) simply never resumes its awaiters.
                bridgeInitDone.completeExceptionally(e)
                throw e
            }
        } else {
            bridgeInitDone.await()
        }
    }

    private inline fun <T> rethrowing(what: String, block: () -> T): T =
        try {
            block()
        } catch (e: UiException) {
            throw IllegalStateException("$what failed: ${e.message}", e)
        }

    // ── Library / crypto helpers (no store required) ─────────────────────────

    /** Library version string (e.g. "0.1.0"). */
    fun getVersion(): String = version()

    data class Keypair(val npub: String, val nsec: String)

    /** Generate a new keypair, throwing on the rare RNG failure. */
    fun generateKeypairTyped(): Keypair = rethrowing("Keypair generation") {
        val kp = generateKeypair()
        Keypair(npub = kp.npub, nsec = kp.nsec)
    }

    /** Derive the npub Bech32 string from a raw nsec Bech32 string, or `null` if invalid. */
    fun getNpubFromNsec(nsec: String): String? = npubFromNsec(nsec)

    /** The human-readable label for a workspace key, or `null` for an unknown one. */
    fun workspaceLabel(workspace: String): String? = ffiWorkspaceLabel(workspace)

    data class WorkspaceInfo(val key: String, val label: String)

    /** Every workspace key and its label (store-free; contrast [currentWorkspaceTyped]). */
    fun workspaces(): List<WorkspaceInfo> =
        allWorkspaces().map { WorkspaceInfo(key = it.key, label = it.label) }

    // ── Vault unlock / lifecycle ─────────────────────────────────────────────

    /**
     * Unlock the vault, returning the active identity's npub, or throwing.
     *
     * Also ensures [initializeEventBridge] has run first — idempotent, so
     * this is a no-op if [mullu.comrade.ComradeApplication] already did it at
     * startup (the common case), but it means correctness here never depends
     * on that startup race having resolved a particular way: whichever of
     * the two calls this, the background feed/DM/call-signal loops this
     * unlock is about to start can never publish an event before a listener
     * is subscribed to receive it.
     */
    fun unlockVaultTyped(path: String, passphrase: String): String = rethrowing("Vault unlock") {
        runBlocking {
            initializeEventBridge()
            ffi.unlockVault(path, passphrase)
        }.npub
    }

    fun isVaultUnlocked(): Boolean = ffi.isVaultUnlocked()

    fun isStoreUnlocked(): Boolean = ffi.isStoreUnlocked()

    /**
     * Re-lock the vault: abort the background feed/DM/sakha loops and drop
     * the store, engines, and in-memory identity/passphrase-derived key (see
     * `comrade_ui::ComradeRuntime::lock_vault`). The caller (see
     * [mullu.comrade.RelayConnectionService]) is responsible for the
     * Android-side half of "locking": stopping the connection service and
     * clearing any UI-held decrypted state — this call only tears down the
     * native side.
     *
     * **Security boundary**: this is the deliberate, user-initiated version
     * of what process death already does by accident to the in-memory vault
     * key. It does not, and cannot, protect against a compromised or rooted
     * device reading process memory before the lock happens — the design
     * goal is a background-but-unlocked window with a real, honest "off"
     * switch, not a stronger guarantee than that.
     */
    fun lockVaultTyped() {
        runBlocking { ffi.lockVault() }
    }

    // ── Identity / workspace controller ──────────────────────────────────────

    fun generateIdentityTyped(): String = rethrowing("Generate identity") { ffi.generateIdentity().npub }

    fun currentIdentityTyped(): String? = ffi.currentIdentity()?.npub

    fun currentWorkspaceTyped(): WorkspaceInfo = ffi.currentWorkspace().let { WorkspaceInfo(it.key, it.label) }

    /** Toggle the active workspace, enforcing the transition state machine. */
    fun toggleWorkspaceTyped(target: String): WorkspaceInfo = rethrowing("Toggle workspace") {
        runBlocking { ffi.toggleWorkspace(target) }.let { WorkspaceInfo(it.key, it.label) }
    }

    fun backTyped(): WorkspaceInfo = runBlocking { ffi.back() }.let { WorkspaceInfo(it.key, it.label) }

    data class MeshStatus(val active: Boolean, val peerCount: Int)

    /**
     * Snapshot of the off-grid Saathi mesh's live status, for seeding
     * [mullu.comrade.MeshStatusMonitor] before the first
     * `BridgeEvent.MeshStatusChanged` arrives. Never throws.
     */
    fun meshStatusTyped(): MeshStatus =
        ffi.meshStatus().let { MeshStatus(active = it.active, peerCount = it.peerCount.toInt()) }

    data class UpiIntent(val amountInr: Double, val vpa: String, val uri: String)

    fun extractPaymentsTyped(text: String): List<UpiIntent> = rethrowing("Extract payments") {
        ffi.extractPayments(text).map { UpiIntent(amountInr = it.amountInr, vpa = it.vpa, uri = it.uri) }
    }

    // ── Sabha (public feed) ───────────────────────────────────────────────────

    data class ChitthiInfo(
        val id: String,
        val author: String,
        val content: String,
        val createdAt: Long,
        val replyTo: String?,
    )

    /** The cached Sabha timeline. */
    fun sabhaTimeline(): List<ChitthiInfo> = rethrowing("Timeline fetch") {
        ffi.fetchSabhaTimeline().map {
            ChitthiInfo(
                id = it.id,
                author = it.author,
                content = it.content,
                createdAt = it.createdAt.toLong(),
                replyTo = it.replyTo,
            )
        }
    }

    /** Broadcast a Chitthi, returning the new event id or throwing on error. */
    fun broadcastChitthiTyped(content: String, replyTo: String = ""): String = rethrowing("Broadcast") {
        runBlocking { ffi.broadcastChitthi(content, replyTo.ifBlank { null }) }
    }

    // ── Vault (E2E DMs) ────────────────────────────────────────────────────────

    data class Profile(val npub: String, val username: String?)

    data class FoundProfile(val npub: String, val name: String?, val about: String?)

    data class ContactInfo(val npub: String, val alias: String, val name: String?)

    data class ConversationInfo(
        val peer: String,
        val alias: String?,
        val peerName: String?,
        val lastMessage: String,
        val lastAt: Long,
        val lastOutgoing: Boolean,
    )

    data class MessageInfo(
        val id: String,
        val peer: String,
        val content: String,
        val createdAt: Long,
        val outgoing: Boolean,
        val status: String? = null,
        val replyTo: String? = null,
    )

    private fun uniffi.comrade_ui.MessageDto.toInfo() = MessageInfo(
        id = id,
        peer = peer,
        content = content,
        createdAt = createdAt.toLong(),
        outgoing = outgoing,
        status = status,
        replyTo = replyTo,
    )

    /** Send a DM, returning the stored message or throwing the backend error. */
    fun sendDmTyped(target: String, content: String): MessageInfo = rethrowing("Send") {
        runBlocking { ffi.sendDm(target, content) }.toInfo()
    }

    /** Send a reply DM ([replyTo] null/blank for a normal message). */
    fun sendDmReplyTyped(target: String, content: String, replyTo: String?): MessageInfo =
        rethrowing("Send") {
            runBlocking { ffi.sendDmReply(target, content, replyTo?.ifBlank { null }) }.toInfo()
        }

    /** The chat list, newest thread first. */
    fun conversations(): List<ConversationInfo> = rethrowing("Conversations") {
        ffi.conversations().map {
            ConversationInfo(
                peer = it.peer,
                alias = it.alias,
                peerName = it.peerName,
                lastMessage = it.lastMessage,
                lastAt = it.lastAt.toLong(),
                lastOutgoing = it.lastOutgoing,
            )
        }
    }

    /** Message history with [peer], oldest first. */
    fun messages(peer: String): List<MessageInfo> =
        rethrowing("Messages") { ffi.messagesWith(peer).map { it.toInfo() } }

    // ── Message requests + receipts ──────────────────────────────────────────

    data class MessageRequestInfo(val peer: String, val lastMessage: String, val lastAt: Long)

    fun messageRequestsTyped(): List<MessageRequestInfo> = rethrowing("Requests") {
        ffi.messageRequests().map {
            MessageRequestInfo(peer = it.peer, lastMessage = it.lastMessage, lastAt = it.lastAt.toLong())
        }
    }

    fun acceptRequestTyped(peer: String) {
        rethrowing("Accept") { runBlocking { ffi.acceptRequest(peer) } }
    }

    fun blockConversationTyped(peer: String) {
        rethrowing("Block") { ffi.blockConversation(peer) }
    }

    fun markConversationReadTyped(peer: String) {
        rethrowing("Mark read") { runBlocking { ffi.markConversationRead(peer) } }
    }

    // ── Profile & contacts ────────────────────────────────────────────────────

    private fun uniffi.comrade_ui.ProfileDto.toInfo() = Profile(npub = npub, username = username)

    fun setUsernameTyped(name: String): Profile =
        rethrowing("Username") { runBlocking { ffi.setUsername(name) }.toInfo() }

    fun currentProfileTyped(): Profile = rethrowing("Profile") { ffi.profile().toInfo() }

    fun searchProfilesTyped(query: String): List<FoundProfile> = rethrowing("Search") {
        runBlocking { ffi.searchProfiles(query) }.map {
            FoundProfile(npub = it.npub, name = it.name, about = it.about)
        }
    }

    private fun uniffi.comrade_ui.ContactDto.toInfo() = ContactInfo(npub = npub, alias = alias, name = name)

    fun addContactTyped(npub: String, alias: String): ContactInfo =
        rethrowing("Add contact") { ffi.addContact(npub, alias).toInfo() }

    fun setContactAliasTyped(npub: String, alias: String): ContactInfo =
        rethrowing("Set alias") { ffi.setContactAlias(npub, alias).toInfo() }

    fun removeContactTyped(npub: String): Boolean = rethrowing("Remove contact") { ffi.removeContact(npub) }

    fun refreshPeerProfilesTyped(): Int = rethrowing("Profile refresh") {
        runBlocking { ffi.refreshPeerProfiles() }.toInt()
    }

    fun contacts(): List<ContactInfo> = rethrowing("Contacts") { ffi.listContacts().map { it.toInfo() } }

    // ── Journal (strictly local) ──────────────────────────────────────────────

    data class JournalEntryInfo(val id: String, val text: String, val mood: String?, val createdAt: Long)

    private fun uniffi.comrade_ui.JournalEntryDto.toInfo() =
        JournalEntryInfo(id = id, text = text, mood = mood, createdAt = createdAt.toLong())

    fun addJournalEntryTyped(text: String, mood: String?): JournalEntryInfo =
        rethrowing("Journal") { ffi.addJournalEntry(text, mood?.ifBlank { null }).toInfo() }

    fun journal(): List<JournalEntryInfo> =
        rethrowing("Journal") { ffi.journalEntries().map { it.toInfo() } }

    fun deleteJournalEntryTyped(id: String): Boolean =
        rethrowing("Journal delete") { ffi.deleteJournalEntry(id) }

    // ── Encrypted media (NIP-94/96 · Blossom) ─────────────────────────────────

    /** An encrypted-media message (send result, incoming reference, or history entry). */
    data class MediaMessageInfo(
        val eventId: String,
        val url: String,
        val mimeType: String,
        val caption: String,
        val sender: String,
        val createdAt: Long,
        val size: Long,
        /** Whether *this device* sent it — mirrors [MessageInfo.outgoing]. */
        val outgoing: Boolean,
    )

    data class MediaBytesInfo(val mimeType: String, val base64: String)

    private fun uniffi.comrade_ui.MediaMessageDto.toInfo() = MediaMessageInfo(
        eventId = eventId,
        url = url,
        mimeType = mimeType,
        caption = caption,
        sender = sender,
        createdAt = createdAt.toLong(),
        size = size.toLong(),
        outgoing = outgoing,
    )

    /**
     * Full encrypted-media history with [peer], oldest first (named `media`,
     * not `mediaWith`, to avoid clashing with the native declaration of the
     * same parameter shape — matching the [messagesWith]/[messages] pattern).
     */
    fun media(peer: String): List<MediaMessageInfo> =
        rethrowing("Media history") { ffi.mediaWith(peer).map { it.toInfo() } }

    /** Encrypt + send raw media bytes (no base64 round-trip — uniffi carries `ByteArray` natively). */
    fun sendMediaBytesTyped(
        target: String,
        mimeType: String,
        caption: String,
        bytes: ByteArray,
    ): MediaMessageInfo = rethrowing("Send media") {
        val dto = runBlocking { ffi.uploadAndSendMedia(target, bytes, mimeType, caption) }
        dto.toInfo()
    }

    /** Download + decrypt a media reference by event id. */
    fun downloadMediaTyped(eventId: String): MediaBytesInfo = rethrowing("Media download") {
        val dto = runBlocking { ffi.downloadAndDecryptMedia(eventId) }
        MediaBytesInfo(mimeType = dto.mimeType, base64 = dto.base64)
    }

    // ── Calls (voice/video signaling) ─────────────────────────────────────────
    //
    // The call UI lives in `call/CallManager.kt` (state machine + WebRTC) and
    // `call/CallScreen.kt` (Compose UI); both consume the same typed enums
    // `Comrade` itself does (`CallMediaKind`, `HangupReason`, `CallSignal`)
    // rather than the old JNI bridge's ad hoc strings — a compiler-checked
    // contract for that wiring.

    data class IceServerInfo(val urls: List<String>, val username: String?, val credential: String?)

    private fun uniffi.comrade_ui.IceServerDto.toInfo() =
        IceServerInfo(urls = urls, username = username, credential = credential)

    fun callIceServersTyped(): List<IceServerInfo> = ffi.callIceServers().map { it.toInfo() }

    fun callIceServersForTyped(strategy: IceStrategy): List<IceServerInfo> =
        ffi.callIceServersFor(strategy).map { it.toInfo() }

    /**
     * The 4-emoji short authentication string (SAS) both call participants
     * should read aloud and compare to catch a man-in-the-middle — derived
     * from the two sides' already-negotiated SDP fingerprints. `null`/empty
     * when either side's SDP had no fingerprint to derive one from; that is
     * a valid "can't verify" outcome, not an error, so this never throws.
     */
    fun callSasTyped(localSdp: String, remoteSdp: String): List<String>? = ffi.callSas(localSdp, remoteSdp)

    /**
     * Configure (or, with a blank [url], clear) the TURN relay. Throws with a
     * user-safe message (never the credential) if [url] isn't a well-formed
     * `turn:`/`turns:` URI — see `comrade_core::call::validate_turn_url`.
     * [username]/[credential] are write-only from here on: nothing in this
     * facade ever logs them or reads them back (see [turnServerStatusTyped]).
     */
    fun setTurnServerTyped(url: String, username: String, credential: String) {
        rethrowing("TURN config") { ffi.setTurnServer(url, username, credential) }
    }

    /** A relay's URL only — never the username/credential. See [TurnServerStatus]. */
    data class TurnServerStatus(val configured: Boolean, val url: String?)

    /**
     * The "is a relay configured" diagnostic for a support/settings screen —
     * safe to display or log as-is, unlike the write-only credential
     * [setTurnServerTyped] takes. Never throws (a locked vault is simply
     * reported as "not configured", matching the Rust side).
     */
    fun turnServerStatusTyped(): TurnServerStatus =
        ffi.turnServerStatus().let { TurnServerStatus(configured = it.configured, url = it.url) }

    data class CallSessionInfo(
        val callId: String,
        val peer: String,
        val media: String,
        val iceServers: List<IceServerInfo>,
    )

    fun placeCallTyped(peer: String, media: CallMediaKind): CallSessionInfo = rethrowing("Place call") {
        val dto = ffi.placeCall(peer, media)
        CallSessionInfo(
            callId = dto.callId,
            peer = dto.peer,
            media = dto.media,
            iceServers = dto.iceServers.map { it.toInfo() },
        )
    }

    fun sendCallSignalTyped(peer: String, callId: String, media: CallMediaKind, signal: CallSignal) {
        rethrowing("Call signal") { runBlocking { ffi.sendCallSignal(peer, callId, media, signal) } }
    }

    fun hangupCallTyped(peer: String, callId: String, media: CallMediaKind, reason: HangupReason) {
        rethrowing("Hangup") { runBlocking { ffi.hangupCall(peer, callId, media, reason) } }
    }

    data class CallRecordInfo(
        val id: String,
        val peer: String,
        val media: String,
        val incoming: Boolean,
        val outcome: String,
        val startedAt: Long,
        val durationSecs: Long,
    )

    private fun uniffi.comrade_ui.CallRecordDto.toInfo() = CallRecordInfo(
        id = id,
        peer = peer,
        media = media,
        incoming = incoming,
        outcome = outcome,
        startedAt = startedAt.toLong(),
        durationSecs = durationSecs.toLong(),
    )

    fun logCallTyped(
        peer: String,
        callId: String,
        media: CallMediaKind,
        incoming: Boolean,
        outcome: String,
        startedAt: Long,
        durationSecs: Long,
    ): CallRecordInfo = rethrowing("Log call") {
        ffi.logCall(peer, callId, media, incoming, outcome, startedAt.toULong(), durationSecs.toULong()).toInfo()
    }

    fun callHistoryTyped(peer: String? = null): List<CallRecordInfo> =
        rethrowing("Call history") { ffi.callHistory(peer).map { it.toInfo() } }

    // ── Sakha/Sakhi CRDT ledger ────────────────────────────────────────────────

    fun syncLedgerTyped(): String = rethrowing("Sync ledger") { runBlocking { ffi.syncLedger() } }

    // ── Push events ────────────────────────────────────────────────────────────

    /**
     * Non-blocking drain of the next queued [BridgeEvent] — highest priority
     * first (see [EventBus]) — or `null` when empty. Events are pushed live
     * by the native core (see [initializeEventBridge]) into an in-memory
     * queue; this is a local, in-process poll, not an FFI round-trip.
     */
    fun pollEvent(): BridgeEvent? = eventQueue.poll()

    /** Live queue-depth/drop/coalescing/lag counters — see [EventBus.Stats]. */
    val eventBusStats: StateFlow<EventBus.Stats> get() = eventQueue.stats
}

/**
 * Bounded, priority-aware home for events pushed from the native core, fed by
 * [ComradeCore.initializeEventBridge]'s listener and drained by
 * [ComradeCore.pollEvent] (single consumer — see [mullu.comrade.RelayConnectionService]).
 *
 * AUDIT.md COMMS-04 replaces the previous unbounded `ConcurrentLinkedQueue`
 * with three placements ([Placement]), each with a distinct backpressure
 * policy:
 *  - [Placement.Critical] (calls, DMs, message requests): appended, never
 *    dropped. A relay-wide public-feed flood cannot touch these — they queue
 *    in their own bucket, drained before anything else.
 *  - [Placement.Coalesced] (mesh/ledger/profile/receipt status): only the
 *    *latest* per logical key is worth keeping — a stale status a newer one
 *    already superseded is redundant, not lost information, so a fresh
 *    update replaces (rather than queues behind) an already-pending one for
 *    the same key.
 *  - [Placement.Feed] (`IncomingChitthi` only): bounded and lossy by design —
 *    an adversarial or merely busy relay must never be able to grow this
 *    queue (or block the producer) without limit; old, unconsumed Chitthis
 *    are dropped once the feed capacity is reached.
 *
 * All mutation is behind one monitor: [offer] runs on whatever thread the
 * native listener callback fires on (not necessarily a Kotlin coroutine),
 * [poll] runs on the drain loop's thread — the same cross-thread-via-`synchronized`
 * shape [mullu.comrade.call.CallManager] already uses throughout.
 */
class EventBus internal constructor() {
    /**
     * Where one [BridgeEvent] belongs — a single classification per event
     * (rather than two separate "which tier"/"what coalescing key" functions
     * that could silently drift out of sync) so [Placement.Coalesced] and its
     * key can never disagree about which events are coalesced.
     */
    private sealed interface Placement {
        data object Critical : Placement
        data class Coalesced(val key: String) : Placement
        data object Feed : Placement
    }

    private fun placementOf(event: BridgeEvent): Placement = when (event) {
        is BridgeEvent.IncomingChitthi -> Placement.Feed
        is BridgeEvent.MeshStatusChanged -> Placement.Coalesced("mesh_status")
        is BridgeEvent.LedgerUpdated -> Placement.Coalesced("ledger")
        is BridgeEvent.PeerProfileUpdated -> Placement.Coalesced("profile:${event.peer}")
        is BridgeEvent.MessageStatus -> Placement.Coalesced("receipt:${event.peer}")
        // DMs, media, message requests, call signals (offer/answer/ICE/hangup).
        else -> Placement.Critical
    }

    data class Stats(
        val criticalDepth: Int = 0,
        val coalescedDepth: Int = 0,
        val feedDepth: Int = 0,
        val feedDrops: Long = 0,
        val coalesceSuppressions: Long = 0,
        val lastDequeueLagMs: Long = 0,
    )

    private companion object {
        /** Bounded, but generously — a human never produces this many DMs/calls/requests. */
        const val CRITICAL_CAPACITY = 4_000

        /** Small and deliberately lossy — see the class doc. */
        const val FEED_CAPACITY = 300

        const val TAG = "EventBus"
    }

    private val lock = Any()
    private val critical = ArrayDeque<Timestamped>()

    /** Insertion order preserved so coalescing still drains oldest-superseded-key first. */
    private val coalesced = LinkedHashMap<String, Timestamped>()
    private val feed = ArrayDeque<Timestamped>()

    private val _stats = MutableStateFlow(Stats())
    val stats: StateFlow<Stats> = _stats.asStateFlow()

    private class Timestamped(val event: BridgeEvent, val enqueuedAtMs: Long)

    fun offer(event: BridgeEvent) {
        synchronized(lock) {
            val wrapped = Timestamped(event, System.currentTimeMillis())
            when (val placement = placementOf(event)) {
                is Placement.Critical -> {
                    critical.addLast(wrapped)
                    if (critical.size > CRITICAL_CAPACITY) {
                        // Never drop a call/DM/request — but a queue this deep
                        // means the drain loop is stuck (or dead), which is
                        // worth knowing about loudly rather than silently
                        // growing memory forever.
                        Log.e(TAG, "critical event queue exceeded $CRITICAL_CAPACITY — is the drain loop stuck?")
                    }
                }
                is Placement.Coalesced -> {
                    if (coalesced.put(placement.key, wrapped) != null) {
                        _stats.update { it.copy(coalesceSuppressions = it.coalesceSuppressions + 1) }
                    }
                }
                is Placement.Feed -> {
                    if (feed.size >= FEED_CAPACITY) {
                        feed.removeFirst()
                        _stats.update { it.copy(feedDrops = it.feedDrops + 1) }
                    }
                    feed.addLast(wrapped)
                }
            }
            _stats.update {
                it.copy(
                    criticalDepth = critical.size,
                    coalescedDepth = coalesced.size,
                    feedDepth = feed.size,
                )
            }
        }
    }

    /** Highest priority first: critical, then coalesced-status, then feed. */
    fun poll(): BridgeEvent? = synchronized(lock) {
        val wrapped = when {
            critical.isNotEmpty() -> critical.removeFirst()
            coalesced.isNotEmpty() -> {
                val key = coalesced.keys.first()
                coalesced.remove(key)
            }
            feed.isNotEmpty() -> feed.removeFirst()
            else -> null
        } ?: return null
        _stats.update {
            it.copy(
                criticalDepth = critical.size,
                coalescedDepth = coalesced.size,
                feedDepth = feed.size,
                lastDequeueLagMs = System.currentTimeMillis() - wrapped.enqueuedAtMs,
            )
        }
        wrapped.event
    }
}
