// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `pump_bridge_events`, `runtime`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AttachmentRoute`, `ShareVerdictDto`

/// The comrade_jni crate version (e.g. "0.1.0").
String version() => RustLib.instance.api.crateApiVersion();

/// A freshly generated secp256k1 keypair, Bech32-encoded. Standalone — doesn't
/// touch the encrypted store; see [`generate_identity`] and [`unlock_vault`]
/// for the store-backed identity flow every UI screen actually drives.
KeypairDto generateKeypair() => RustLib.instance.api.crateApiGenerateKeypair();

/// Derive the npub from an nsec Bech32 string, or `None` if it doesn't parse.
String? npubFromNsec({required String nsec}) =>
    RustLib.instance.api.crateApiNpubFromNsec(nsec: nsec);

/// The display label for a workspace discriminant, or `None` for an unknown key.
String? workspaceLabel({required String workspace}) =>
    RustLib.instance.api.crateApiWorkspaceLabel(workspace: workspace);

/// Every workspace discriminant and its label — a stable, store-free list
/// (contrast [`workspaces`], which also reports which one is active).
List<WorkspaceKeyLabel> allWorkspaces() =>
    RustLib.instance.api.crateApiAllWorkspaces();

/// Materialise the process-global runtime, if some other caller (e.g. Kotlin
/// constructing `Comrade()`) has not already. The Dart counterpart of
/// `Comrade()`; there is no handle to hold onto because there is nothing to
/// hold — every function below finds the same runtime on its own.
Future<void> initRuntime() => RustLib.instance.api.crateApiInitRuntime();

/// [`init_runtime`], but seeding the runtime with an explicit relay set —
/// AUDIT.md COMMS-03's isolated-relay test hook. Only takes effect if this is
/// what first creates the runtime; the shipping app calls [`init_runtime`].
Future<void> initRuntimeWithRelays({required List<String> relays}) =>
    RustLib.instance.api.crateApiInitRuntimeWithRelays(relays: relays);

/// Open the encrypted store, restore or seed the identity, build the engines,
/// and start the background feed/DM loops. Safe to call more than once
/// (returns the already-loaded identity) — including when the *other* ABI
/// already unlocked it, which is the whole point of the shared runtime.
Future<IdentityDto> unlockVault(
        {required String path, required String passphrase}) =>
    RustLib.instance.api
        .crateApiUnlockVault(path: path, passphrase: passphrase);

Future<bool> isVaultUnlocked() =>
    RustLib.instance.api.crateApiIsVaultUnlocked();

Future<bool> isStoreUnlocked() =>
    RustLib.instance.api.crateApiIsStoreUnlocked();

/// Re-lock the vault: abort the background feed/DM/sakha loops and drop the
/// store, engines, and in-memory identity.
Future<void> lockVault() => RustLib.instance.api.crateApiLockVault();

Future<IdentityDto> generateIdentity() =>
    RustLib.instance.api.crateApiGenerateIdentity();

Future<IdentityDto?> currentIdentity() =>
    RustLib.instance.api.crateApiCurrentIdentity();

Future<List<UpiIntentDto>> extractPayments({required String text}) =>
    RustLib.instance.api.crateApiExtractPayments(text: text);

Future<List<WorkspaceDto>> workspaces() =>
    RustLib.instance.api.crateApiWorkspaces();

Future<WorkspaceDto> currentWorkspace() =>
    RustLib.instance.api.crateApiCurrentWorkspace();

/// Async because switching also starts/stops the Saathi mesh engine to match.
Future<WorkspaceDto> toggleWorkspace({required String target}) =>
    RustLib.instance.api.crateApiToggleWorkspace(target: target);

/// Async for the same reason as [`toggle_workspace`].
Future<WorkspaceDto> back() => RustLib.instance.api.crateApiBack();

/// Snapshot of the off-grid Saathi mesh's live status, for seeding a
/// connectivity indicator before the first `BridgeEvent::MeshStatusChanged`
/// arrives. Never fails: the mesh being off is a valid, common state.
Future<MeshStatusDto> meshStatus() => RustLib.instance.api.crateApiMeshStatus();

Future<List<ChitthiDto>> fetchSabhaTimeline() =>
    RustLib.instance.api.crateApiFetchSabhaTimeline();

/// Takes a cheap, synchronous handle snapshot under the guard and runs the
/// relay round-trip after it is dropped — AUDIT P2: never hold the runtime
/// lock across a network await, or one slow relay stalls every other call.
Future<String> broadcastChitthi({required String content, String? replyTo}) =>
    RustLib.instance.api
        .crateApiBroadcastChitthi(content: content, replyTo: replyTo);

/// Broadcast a Chitthi under a throwaway or scoped persona instead of this
/// device's identity — the anonymous-thoughts path.
///
/// `scope` of `None` signs the post with a key used exactly once, so two
/// anonymous Chitthis cannot be linked to each other. `Some(label)` derives a
/// stable persona for that label, so replies can reach the same pseudonym while
/// it stays unlinkable to the identity. See `docs/BITCHAT_ADOPTION.md` for what
/// this does and does not hide.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<String> broadcastAnonymousChitthi(
        {required String content, String? scope}) =>
    RustLib.instance.api
        .crateApiBroadcastAnonymousChitthi(content: content, scope: scope);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<MessageDto> sendDm({required String target, required String content}) =>
    RustLib.instance.api.crateApiSendDm(target: target, content: content);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<MessageDto> sendDmReply(
        {required String target, required String content, String? replyTo}) =>
    RustLib.instance.api.crateApiSendDmReply(
        target: target, content: content, replyTo: replyTo);

/// React to a message in `peer`'s thread — or take an existing reaction back by
/// passing the same emoji again. Returns the reaction now standing, or `None` if
/// the tap withdrew one.
///
/// The toggle is decided on the Rust side (see `ComradeRuntime::toggle_reaction`)
/// so this frontend and Android cannot disagree about what tapping an
/// already-sent emoji means.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<ReactionDto?> toggleReaction(
        {required String peer,
        required String targetId,
        required String emoji}) =>
    RustLib.instance.api
        .crateApiToggleReaction(peer: peer, targetId: targetId, emoji: emoji);

/// Every reaction in `peer`'s conversation, oldest first, read from the encrypted
/// store — so a thread opens with its reactions already drawn.
Future<List<ReactionDto>> reactions({required String peer}) =>
    RustLib.instance.api.crateApiReactions(peer: peer);

/// Retry every DM sitting in the sender outbox because no relay would take it.
/// Returns how many a relay accepted this pass.
///
/// A background loop already flushes on a cadence (and once at launch); call
/// this when the platform reports connectivity came back, so a queued message
/// goes out immediately instead of on the next tick.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<BigInt> flushOutbox() => RustLib.instance.api.crateApiFlushOutbox();

/// How many DMs are waiting for a relay that will take them — for a "queued"
/// indicator in the chat list.
Future<BigInt> outboxPending() => RustLib.instance.api.crateApiOutboxPending();

/// **Panic wipe.** Destroy every locally stored value — identity keys, DM
/// history, journal, Tara thread, queued mail — then re-lock, leaving the
/// runtime as it was before its first unlock.
///
/// Irreversible, and deliberately not a duress feature: it wipes rather than
/// hides, and it needs the app open and unlocked. After it returns, send the
/// user back to onboarding.
Future<void> panicWipe() => RustLib.instance.api.crateApiPanicWipe();

/// Device-local delivery counters — bare tallies with no identities, ids,
/// content, or timestamps, for a diagnostics screen. Nothing here is ever
/// uploaded; [`panic_wipe`] clears them.
Future<List<MetricDto>> metricsSnapshot() =>
    RustLib.instance.api.crateApiMetricsSnapshot();

Future<List<ConversationDto>> conversations() =>
    RustLib.instance.api.crateApiConversations();

Future<List<MessageDto>> messagesWith({required String peer}) =>
    RustLib.instance.api.crateApiMessagesWith(peer: peer);

/// Every pinned message in `peer`'s conversation, oldest pin first. See
/// `comrade_ui::ComradeRuntime::pinned_messages`.
Future<List<MessageDto>> pinnedMessages({required String peer}) =>
    RustLib.instance.api.crateApiPinnedMessages(peer: peer);

/// Every starred message across every conversation, oldest star first — the
/// "Starred Messages" screen. See `comrade_ui::ComradeRuntime::starred_messages`.
Future<List<MessageDto>> starredMessages() =>
    RustLib.instance.api.crateApiStarredMessages();

/// Star or un-star one of `peer`'s messages. Local device state only; returns
/// whether the stored state changed. See
/// `comrade_ui::ComradeRuntime::star_message`.
Future<bool> starMessage(
        {required String peer,
        required String messageId,
        required bool starred}) =>
    RustLib.instance.api.crateApiStarMessage(
        peer: peer, messageId: messageId, starred: starred);

/// Pin one of `peer`'s messages. Refuses once the conversation is already at
/// the pin cap — unpin one first. `false` (not an error) if it was already
/// pinned. See `comrade_ui::ComradeRuntime::pin_message`.
Future<bool> pinMessage({required String peer, required String messageId}) =>
    RustLib.instance.api.crateApiPinMessage(peer: peer, messageId: messageId);

/// Unpin one of `peer`'s messages. `true` if it was pinned. See
/// `comrade_ui::ComradeRuntime::unpin_message`.
Future<bool> unpinMessage({required String peer, required String messageId}) =>
    RustLib.instance.api.crateApiUnpinMessage(peer: peer, messageId: messageId);

/// Hide one of `peer`'s messages on this device only. See
/// `comrade_ui::ComradeRuntime::delete_message_for_me`.
Future<void> deleteMessageForMe(
        {required String peer, required String messageId}) =>
    RustLib.instance.api
        .crateApiDeleteMessageForMe(peer: peer, messageId: messageId);

/// Delete a message you sent for everyone in `peer`'s conversation — a
/// best-effort courtesy, not a protocol guarantee. See
/// `comrade_ui::ComradeRuntime::delete_message_for_everyone`.
///
/// Not wrapped through [`broadcast_chitthi`]'s `handles()` snapshot:
/// `comrade_ui::ComradeRuntime::delete_message_for_everyone` takes `&self`
/// rather than exposing a `RuntimeHandles` counterpart, so this holds a
/// shared read guard across its network send — the same shape as
/// [`panic_wipe`], not the exclusive-write case that one guards against.
Future<void> deleteMessageForEveryone(
        {required String peer, required String messageId}) =>
    RustLib.instance.api
        .crateApiDeleteMessageForEveryone(peer: peer, messageId: messageId);

/// Forward one of `from_peer`'s messages to each of `to_peers`, as a new
/// message in each conversation. See
/// `comrade_ui::ComradeRuntime::forward_message`.
///
/// Same lock-discipline note as [`delete_message_for_everyone`]: no
/// `RuntimeHandles` counterpart exists for this one either.
Future<List<MessageDto>> forwardMessage(
        {required String fromPeer,
        required String messageId,
        required List<String> toPeers}) =>
    RustLib.instance.api.crateApiForwardMessage(
        fromPeer: fromPeer, messageId: messageId, toPeers: toPeers);

/// Fetch and build a link preview for the first link in `content`, if any —
/// sender-side only, run before a send. Takes no lock: a free function
/// underneath, so this wrapper cannot hold a guard across the network round
/// trip. See `comrade_ui::compose_link_preview`.
Future<LinkPreviewDto?> composeLinkPreview({required String content}) =>
    RustLib.instance.api.crateApiComposeLinkPreview(content: content);

/// Attach `preview` to `content`, producing the body [`send_dm`] should
/// actually send. See `comrade_ui::attach_link_preview`.
String attachLinkPreview(
        {required String content, required LinkPreviewDto preview}) =>
    RustLib.instance.api
        .crateApiAttachLinkPreview(content: content, preview: preview);

/// Full encrypted-media history with `peer`, oldest first — the media
/// counterpart of [`messages_with`].
Future<List<MediaMessageDto>> mediaWith({required String peer}) =>
    RustLib.instance.api.crateApiMediaWith(peer: peer);

/// Every topic in `peer`'s conversation, oldest first, with live counts.
/// Closed ones are included — the archive has to be reachable.
Future<List<TopicDto>> topics({required String peer}) =>
    RustLib.instance.api.crateApiTopics(peer: peer);

/// Every thread in `peer`'s conversation, most recently active first.
/// `topic_slug` of `None` is *all* threads, not the unfiled ones.
Future<List<ThreadSummaryDto>> threads(
        {required String peer, String? topicSlug}) =>
    RustLib.instance.api.crateApiThreads(peer: peer, topicSlug: topicSlug);

/// One thread in full. `root_id` may name any message in it — the walk up the
/// reply chain happens on the Rust side so the frontends cannot disagree about
/// which thread a bubble belongs to.
Future<ThreadDto> thread({required String peer, required String rootId}) =>
    RustLib.instance.api.crateApiThread(peer: peer, rootId: rootId);

/// The id of the thread a message belongs to.
Future<String> threadRoot({required String peer, required String messageId}) =>
    RustLib.instance.api.crateApiThreadRoot(peer: peer, messageId: messageId);

/// Name a topic and tell the peer. Idempotent: naming one that exists returns
/// it, because the slug is the id.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<TopicDto> createTopic({required String peer, required String name}) =>
    RustLib.instance.api.crateApiCreateTopic(peer: peer, name: name);

/// File the thread containing `message_id` under `topic_name`, creating the
/// topic if it is new — or, with `None`, take it out of wherever it was.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<ThreadSummaryDto> assignThread(
        {required String peer, required String messageId, String? topicName}) =>
    RustLib.instance.api.crateApiAssignThread(
        peer: peer, messageId: messageId, topicName: topicName);

/// Archive a topic, or bring it back.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<TopicDto> setTopicClosed(
        {required String peer, required String slug, required bool closed}) =>
    RustLib.instance.api
        .crateApiSetTopicClosed(peer: peer, slug: slug, closed: closed);

/// Reply inside a thread — addressed to the thread's root, whichever message in
/// it the caller happens to name.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<MessageDto> sendThreadReply(
        {required String peer,
        required String rootId,
        required String content}) =>
    RustLib.instance.api
        .crateApiSendThreadReply(peer: peer, rootId: rootId, content: content);

Future<List<MessageRequestDto>> messageRequests() =>
    RustLib.instance.api.crateApiMessageRequests();

/// Async because accepting fires a background profile-share + receipt send
/// that needs a live reactor to `tokio::spawn` onto.
Future<void> acceptRequest({required String peer}) =>
    RustLib.instance.api.crateApiAcceptRequest(peer: peer);

Future<void> blockConversation({required String peer}) =>
    RustLib.instance.api.crateApiBlockConversation(peer: peer);

/// Async for the same reason as [`accept_request`].
///
/// Returns the read position the thread had *before* this call (unix seconds,
/// 0 = never opened), so the UI can open at the first unread message.
Future<BigInt> markConversationRead({required String peer}) =>
    RustLib.instance.api.crateApiMarkConversationRead(peer: peer);

Future<ProfileDto> profile() => RustLib.instance.api.crateApiProfile();

Future<ProfileDto> setUsername({required String name}) =>
    RustLib.instance.api.crateApiSetUsername(name: name);

/// Set (or clear, with an empty string) this identity's bio, and republish.
Future<ProfileDto> setAbout({required String about}) =>
    RustLib.instance.api.crateApiSetAbout(about: about);

/// Everything a profile page draws for one peer, from the local cache alone —
/// no relay round trip, so it answers offline and immediately.
Future<PeerProfileDto> peerProfile({required String npub}) =>
    RustLib.instance.api.crateApiPeerProfile(npub: npub);

/// A peer's cached avatar bytes, or `None` to draw initials. Reads the encrypted
/// store and never the network, so calling it discloses nothing to anyone.
Future<MediaBytesDto?> peerAvatar({required String npub}) =>
    RustLib.instance.api.crateApiPeerAvatar(npub: npub);

/// Whether peer-published pictures may be fetched at all (default on).
Future<bool> remoteAvatarsEnabled() =>
    RustLib.instance.api.crateApiRemoteAvatarsEnabled();

Future<void> setRemoteAvatarsEnabled({required bool on_}) =>
    RustLib.instance.api.crateApiSetRemoteAvatarsEnabled(on_: on_);

Future<ContactDto> addContact({required String npub, required String alias}) =>
    RustLib.instance.api.crateApiAddContact(npub: npub, alias: alias);

Future<ContactDto> setContactAlias(
        {required String npub, required String alias}) =>
    RustLib.instance.api.crateApiSetContactAlias(npub: npub, alias: alias);

Future<bool> removeContact({required String npub}) =>
    RustLib.instance.api.crateApiRemoveContact(npub: npub);

Future<List<ContactDto>> listContacts() =>
    RustLib.instance.api.crateApiListContacts();

/// See [`broadcast_chitthi`] for the lock discipline.
Future<List<FoundProfileDto>> searchProfiles({required String query}) =>
    RustLib.instance.api.crateApiSearchProfiles(query: query);

/// Detaches the refresher and drops the shared lock before the relay
/// round-trip (AUDIT P2).
Future<BigInt> refreshPeerProfiles() =>
    RustLib.instance.api.crateApiRefreshPeerProfiles();

/// Choose (or un-choose) a contact as a comrade.
///
/// What this discloses, stated plainly: from now on this device tells *that one
/// peer* — nobody else, and no relay — when it is online, and it starts
/// believing what they say about their own presence. It does **not** subscribe
/// us to theirs; we see them only once they have marked us back, which is what
/// [`ComradeDto`]'s `peer_marked_us` is for.
///
/// Async for the same reason as [`accept_request`]: the beacon telling that
/// peer about the change is a background `tokio::spawn`, which needs a live
/// reactor.
Future<ContactDto> setComrade({required String npub, required bool comrade}) =>
    RustLib.instance.api.crateApiSetComrade(npub: npub, comrade: comrade);

/// Every comrade with their live presence, online first.
Future<List<ComradeDto>> comrades() => RustLib.instance.api.crateApiComrades();

/// One peer's live presence, or `None` if no beacon ever arrived from them
/// (they haven't chosen us back, or haven't been online since).
Future<PresenceDto?> peerPresence({required String npub}) =>
    RustLib.instance.api.crateApiPeerPresence(npub: npub);

/// Announce this device's presence to every comrade, returning how many beacons
/// a relay accepted. Frontends call this on foreground/background transitions;
/// the native heartbeat covers the rest. Never fails — presence is a courtesy,
/// so a locked vault is a quiet `0`, not an error.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<BigInt> announcePresence({required bool online}) =>
    RustLib.instance.api.crateApiAnnouncePresence(online: online);

/// There is unsent text in `peer`'s composer, as of now.
///
/// What this discloses, stated plainly: nothing, yet. It starts a local clock.
/// If the draft is later abandoned — cleared, or left behind when the thread
/// closes — and `peer` is a comrade, their device is told *that it happened*
/// and nothing else: never the text, its length, or how the writing ended.
/// See `comrade_core::nudge` for every rule that has to agree first.
///
/// Cheap enough to call on a keystroke, and infallible: a courtesy signal has
/// no business raising an error into a text field. Synchronous for the same
/// reason — the work is a hash-map insert, so an async hop would cost more than
/// the thing it was scheduling.
///
/// `try_read` rather than a blocking acquire: nothing about watching a composer
/// is worth waiting behind a slow `lock_vault`/`unlock_vault` for, and a skipped
/// report costs at most one nudge (the next keystroke reports again).
Future<void> noteDraft({required String peer}) =>
    RustLib.instance.api.crateApiNoteDraft(peer: peer);

/// That draft is gone — cleared, or left behind when the thread closed. Call it
/// whenever a conversation closes; a composer that never held text does
/// nothing.
///
/// Skipped under contention like [`note_draft`], which fails in the harmless
/// direction: locking the vault clears the watch regardless.
Future<void> abandonDraft({required String peer}) =>
    RustLib.instance.api.crateApiAbandonDraft(peer: peer);

/// Tell every comrade, once, that this person might need them — the deliberate
/// trigger behind the breathing screen.
///
/// What this discloses, stated plainly: each comrade — nobody else, and no
/// relay — is told that you might need them, and *nothing else*. It is the same
/// envelope an abandoned draft sends, so they cannot tell which happened, and
/// it shares that trigger's cooldown so the two can never add up to two
/// notifications. Nothing is stored locally about having done it.
///
/// Returns how many nudges a relay accepted; `0` when no comrades are chosen.
/// Never fails — like presence, this is a courtesy.
Future<BigInt> nudgeComrades() => RustLib.instance.api.crateApiNudgeComrades();

Future<JournalEntryDto> addJournalEntry({required String text, String? mood}) =>
    RustLib.instance.api.crateApiAddJournalEntry(text: text, mood: mood);

/// Save a journal entry that is a recording — a voice entry or a video entry the
/// frontend has already written to its own directory for that kind. The core
/// never opens, moves or deletes that file — see `JournalRecordingDto` for the
/// split and what it costs. `recording.mime` is what picks the player, and it
/// may not be blank.
Future<JournalEntryDto> addJournalRecording(
        {String? title,
        required String text,
        String? mood,
        required JournalRecordingDto recording}) =>
    RustLib.instance.api.crateApiAddJournalRecording(
        title: title, text: text, mood: mood, recording: recording);

/// Rename an entry, or clear the title with `None`. `None` back means no entry
/// has that id. Only the title changes — not the words, the mood, the recording
/// or when it was written.
Future<JournalEntryDto?> setJournalEntryTitle(
        {required String id, String? title}) =>
    RustLib.instance.api.crateApiSetJournalEntryTitle(id: id, title: title);

Future<List<JournalEntryDto>> journalEntries() =>
    RustLib.instance.api.crateApiJournalEntries();

/// Remove an entry. For a recording entry this removes the record only: the file is
/// the frontend's and the frontend must delete it too.
Future<bool> deleteJournalEntry({required String id}) =>
    RustLib.instance.api.crateApiDeleteJournalEntry(id: id);

/// Hand one journal entry to one peer, as an ordinary DM. A copy: the entry is
/// not marked, moved or changed — see `RuntimeHandles::share_journal_entry`.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<MessageDto> shareJournalEntry(
        {required String peer, required String entryId}) =>
    RustLib.instance.api
        .crateApiShareJournalEntry(peer: peer, entryId: entryId);

/// Persist the user's message, compute Tara's on-device reply, persist and
/// return it. `crisis == true` on the reply means the UI must surface
/// [`tara_crisis_resources`] with it.
Future<TaraMessageDto> taraSend({required String text}) =>
    RustLib.instance.api.crateApiTaraSend(text: text);

/// The whole Tara thread, oldest-first (chat order).
Future<List<TaraMessageDto>> taraThread() =>
    RustLib.instance.api.crateApiTaraThread();

/// Delete the entire Tara thread; returns how many turns were removed.
Future<BigInt> clearTaraThread() =>
    RustLib.instance.api.crateApiClearTaraThread();

/// The opener shown while the thread is empty — shaped by recent journal mood
/// markers only, never entry text.
Future<String> taraOpener() => RustLib.instance.api.crateApiTaraOpener();

/// The crisis helplines Tara hands off to.
Future<List<CrisisResourceDto>> taraCrisisResources() =>
    RustLib.instance.api.crateApiTaraCrisisResources();

Future<List<IceServerDto>> callIceServers() =>
    RustLib.instance.api.crateApiCallIceServers();

Future<List<IceServerDto>> callIceServersFor({required IceStrategy strategy}) =>
    RustLib.instance.api.crateApiCallIceServersFor(strategy: strategy);

/// The 4-emoji short authentication string (SAS) for the in-progress call
/// whose local/remote SDPs are `local_sdp`/`remote_sdp`. `None` when either
/// side's SDP carries no `a=fingerprint:` line to derive a code from.
Future<List<String>?> callSas(
        {required String localSdp, required String remoteSdp}) =>
    RustLib.instance.api
        .crateApiCallSas(localSdp: localSdp, remoteSdp: remoteSdp);

Future<void> setTurnServer(
        {required String url,
        required String username,
        required String credential}) =>
    RustLib.instance.api.crateApiSetTurnServer(
        url: url, username: username, credential: credential);

/// The "is a relay configured" diagnostic status. Carries the URL only; never
/// the username/credential.
Future<TurnServerStatusDto> turnServerStatus() =>
    RustLib.instance.api.crateApiTurnServerStatus();

Future<CallSessionDto> placeCall(
        {required String peer, required CallMediaKind media}) =>
    RustLib.instance.api.crateApiPlaceCall(peer: peer, media: media);

/// `signal` crosses as the real [`CallSignal`] enum, not a JSON blob — only
/// this crate still round-trips it through JSON internally, since that's the
/// wire format the encrypted DM channel carries.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<void> sendCallSignal(
        {required String peer,
        required String callId,
        required CallMediaKind media,
        required CallSignal signal}) =>
    RustLib.instance.api.crateApiSendCallSignal(
        peer: peer, callId: callId, media: media, signal: signal);

/// Classify the ICE candidate pair a transfer connection selected.
Future<IcePathKind> shareClassifyPath(
        {required String localType, required String remoteType}) =>
    RustLib.instance.api.crateApiShareClassifyPath(
        localType: localType, remoteType: remoteType);

/// Whether a transfer over `path` may proceed under `policy` — see the uniffi twin.
///
/// `consent_granted` answers a question a previous call asked by returning
/// `NeedsConsent`. It can only turn that into `Allow`; a refusal stays refused
/// however insistently a frontend claims consent.
Future<TransferVerdict> shareTransferVerdict(
        {required IcePathKind path,
        required BigInt totalBytes,
        required RelayPolicy policy,
        required bool consentGranted}) =>
    RustLib.instance.api.crateApiShareTransferVerdict(
        path: path,
        totalBytes: totalBytes,
        policy: policy,
        consentGranted: consentGranted);

/// Whether a transfer connection built under `policy` may be offered TURN.
Future<bool> shareIceServersAllowed({required RelayPolicy policy}) =>
    RustLib.instance.api.crateApiShareIceServersAllowed(policy: policy);

/// Recognise a Spotify / Apple Music / YouTube link. Pure and offline.
Future<MusicLink?> parseMusicLink({required String input}) =>
    RustLib.instance.api.crateApiParseMusicLink(input: input);

/// Score a library candidate against what the peer named — see the uniffi twin.
Future<double> togetherMatchScore(
        {required Recording want,
        required Recording have,
        required BigInt wantMs,
        required BigInt haveMs}) =>
    RustLib.instance.api.crateApiTogetherMatchScore(
        want: want, have: have, wantMs: wantMs, haveMs: haveMs);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<TogetherSessionDto> togetherStart(
        {required String peer, required TogetherContent content}) =>
    RustLib.instance.api.crateApiTogetherStart(peer: peer, content: content);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<void> togetherJoin() => RustLib.instance.api.crateApiTogetherJoin();

/// See [`broadcast_chitthi`] for the lock discipline.
Future<void> togetherSetState(
        {required BigInt posMs,
        required bool playing,
        required BigInt effectiveInMs}) =>
    RustLib.instance.api.crateApiTogetherSetState(
        posMs: posMs, playing: playing, effectiveInMs: effectiveInMs);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<void> togetherEnd() => RustLib.instance.api.crateApiTogetherEnd();

/// Report where our own player is. Synchronous and skipped under contention —
/// see [`Comrade::together_report_position`] in this crate's uniffi half.
Future<void> togetherReportPosition(
        {required BigInt posMs,
        required bool playing,
        required BigInt outputLatencyMs}) =>
    RustLib.instance.api.crateApiTogetherReportPosition(
        posMs: posMs, playing: playing, outputLatencyMs: outputLatencyMs);

/// Declare whether a direct peer channel is carrying this session — see
/// [`Comrade::together_direct_ready`] in this crate's uniffi half.
Future<void> togetherDirectReady({required bool ready}) =>
    RustLib.instance.api.crateApiTogetherDirectReady(ready: ready);

/// Hand over an envelope that arrived on the direct channel — see
/// [`Comrade::together_receive_direct`] in this crate's uniffi half.
Future<void> togetherReceiveDirect({required String json}) =>
    RustLib.instance.api.crateApiTogetherReceiveDirect(json: json);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<void> hangupCall(
        {required String peer,
        required String callId,
        required CallMediaKind media,
        required HangupReason reason}) =>
    RustLib.instance.api.crateApiHangupCall(
        peer: peer, callId: callId, media: media, reason: reason);

Future<CallRecordDto> logCall(
        {required String peer,
        required String callId,
        required CallMediaKind media,
        required bool incoming,
        required String outcome,
        required BigInt startedAt,
        required BigInt durationSecs}) =>
    RustLib.instance.api.crateApiLogCall(
        peer: peer,
        callId: callId,
        media: media,
        incoming: incoming,
        outcome: outcome,
        startedAt: startedAt,
        durationSecs: durationSecs);

Future<List<CallRecordDto>> callHistory({String? peer}) =>
    RustLib.instance.api.crateApiCallHistory(peer: peer);

/// `bytes` crosses as a native byte array.
///
/// See [`broadcast_chitthi`] for the lock discipline.
Future<MediaMessageDto> uploadAndSendMedia(
        {required String targetPubkey,
        required List<int> bytes,
        required String mimeType,
        required String caption}) =>
    RustLib.instance.api.crateApiUploadAndSendMedia(
        targetPubkey: targetPubkey,
        bytes: bytes,
        mimeType: mimeType,
        caption: caption);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<MediaBytesDto> downloadAndDecryptMedia({required String eventId}) =>
    RustLib.instance.api.crateApiDownloadAndDecryptMedia(eventId: eventId);

/// See [`broadcast_chitthi`] for the lock discipline.
Future<String> syncLedger() => RustLib.instance.api.crateApiSyncLedger();

/// Every [`BridgeEvent`], as a Dart `Stream`.
///
/// The Dart counterpart of `Comrade::set_event_listener`, and deliberately
/// sourced from the *same* two `tokio::sync::broadcast` channels the uniffi
/// listener forwards — `broadcast` fans out to every receiver, so a Kotlin
/// service listening through uniffi and a Flutter UI listening through this
/// stream both see every event, simultaneously, with neither starving the
/// other.
///
/// Two channels are merged, exactly as `set_event_listener` forwards two:
/// the critical stream (DMs, requests, call signals, mesh/ledger updates) and
/// the separate, small, deliberately-lossy `IncomingChitthi` feed stream (see
/// `comrade_ui::ComradeRuntime::subscribe_feed_events`, AUDIT.md COMMS-04), so
/// a public-feed flood can never delay a call signal queued behind it.
///
/// Subscribing late is safe but not retroactive: `broadcast` receivers only
/// see events sent after they subscribe, so call this before [`unlock_vault`].
/// Dropping the Dart subscription ends the task.
Stream<BridgeEvent> bridgeEventStream() =>
    RustLib.instance.api.crateApiBridgeEventStream();

class AttachmentHandoff {
  final ShareOffer shape;
  final String mimeType;
  final String fileName;
  final String caption;

  const AttachmentHandoff({
    required this.shape,
    required this.mimeType,
    required this.fileName,
    required this.caption,
  });

  @override
  int get hashCode =>
      shape.hashCode ^ mimeType.hashCode ^ fileName.hashCode ^ caption.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentHandoff &&
          runtimeType == other.runtimeType &&
          shape == other.shape &&
          mimeType == other.mimeType &&
          fileName == other.fileName &&
          caption == other.caption;
}

class AttachmentHandoffDto {
  final String transferId;
  final String peer;
  final HandoffSignal signal;

  const AttachmentHandoffDto({
    required this.transferId,
    required this.peer,
    required this.signal,
  });

  @override
  int get hashCode => transferId.hashCode ^ peer.hashCode ^ signal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentHandoffDto &&
          runtimeType == other.runtimeType &&
          transferId == other.transferId &&
          peer == other.peer &&
          signal == other.signal;
}

@freezed
sealed class BridgeEvent with _$BridgeEvent {
  const BridgeEvent._();

  const factory BridgeEvent.incomingChitthi(
    ChitthiDto field0,
  ) = BridgeEvent_IncomingChitthi;
  const factory BridgeEvent.incomingDirectMessage(
    DirectMessageDto field0,
  ) = BridgeEvent_IncomingDirectMessage;
  const factory BridgeEvent.incomingMedia(
    MediaMessageDto field0,
  ) = BridgeEvent_IncomingMedia;
  const factory BridgeEvent.incomingReaction(
    ReactionDto field0,
  ) = BridgeEvent_IncomingReaction;
  const factory BridgeEvent.incomingCallSignal(
    CallSignalDto field0,
  ) = BridgeEvent_IncomingCallSignal;
  const factory BridgeEvent.incomingMessageRequest(
    MessageRequestDto field0,
  ) = BridgeEvent_IncomingMessageRequest;
  const factory BridgeEvent.messageStatus({
    required String peer,
    required List<String> messageIds,
    required String status,
  }) = BridgeEvent_MessageStatus;
  const factory BridgeEvent.peerProfileUpdated({
    required String peer,
    String? name,
  }) = BridgeEvent_PeerProfileUpdated;
  const factory BridgeEvent.comradePresence({
    required String peer,
    String? name,
    required bool online,
    required BigInt at,
  }) = BridgeEvent_ComradePresence;
  const factory BridgeEvent.comradeNudge({
    required String peer,
    String? name,
  }) = BridgeEvent_ComradeNudge;
  const factory BridgeEvent.rideSignal(
    RideSignalDto field0,
  ) = BridgeEvent_RideSignal;
  const factory BridgeEvent.togetherInvited(
    TogetherInviteDto field0,
  ) = BridgeEvent_TogetherInvited;
  const factory BridgeEvent.togetherJoined({
    required String sessionId,
    required String peer,
  }) = BridgeEvent_TogetherJoined;
  const factory BridgeEvent.togetherCommand(
    TogetherCommandDto field0,
  ) = BridgeEvent_TogetherCommand;
  const factory BridgeEvent.togetherCorrection(
    TogetherCorrectionDto field0,
  ) = BridgeEvent_TogetherCorrection;
  const factory BridgeEvent.togetherEnded({
    required String sessionId,
    required String peer,
    required bool byPeer,
  }) = BridgeEvent_TogetherEnded;
  const factory BridgeEvent.togetherShare(
    TogetherShareDto field0,
  ) = BridgeEvent_TogetherShare;
  const factory BridgeEvent.togetherOutbound({
    required String sessionId,
    required String json,
  }) = BridgeEvent_TogetherOutbound;
  const factory BridgeEvent.attachmentHandoff(
    AttachmentHandoffDto field0,
  ) = BridgeEvent_AttachmentHandoff;
  const factory BridgeEvent.meshStatusChanged(
    MeshStatusDto field0,
  ) = BridgeEvent_MeshStatusChanged;
  const factory BridgeEvent.ledgerUpdated({
    required String ledger,
  }) = BridgeEvent_LedgerUpdated;
  const factory BridgeEvent.topicsChanged({
    required String peer,
  }) = BridgeEvent_TopicsChanged;
}

enum CallMediaKind {
  audio,
  video,
  ;
}

class CallRecordDto {
  final String id;
  final String peer;
  final String media;
  final bool incoming;
  final String outcome;
  final BigInt startedAt;
  final BigInt durationSecs;

  const CallRecordDto({
    required this.id,
    required this.peer,
    required this.media,
    required this.incoming,
    required this.outcome,
    required this.startedAt,
    required this.durationSecs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      peer.hashCode ^
      media.hashCode ^
      incoming.hashCode ^
      outcome.hashCode ^
      startedAt.hashCode ^
      durationSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallRecordDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          peer == other.peer &&
          media == other.media &&
          incoming == other.incoming &&
          outcome == other.outcome &&
          startedAt == other.startedAt &&
          durationSecs == other.durationSecs;
}

class CallSessionDto {
  final String callId;
  final String peer;
  final String media;
  final List<IceServerDto> iceServers;

  const CallSessionDto({
    required this.callId,
    required this.peer,
    required this.media,
    required this.iceServers,
  });

  @override
  int get hashCode =>
      callId.hashCode ^ peer.hashCode ^ media.hashCode ^ iceServers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallSessionDto &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          peer == other.peer &&
          media == other.media &&
          iceServers == other.iceServers;
}

@freezed
sealed class CallSignal with _$CallSignal {
  const CallSignal._();

  const factory CallSignal.offer({
    required String sdp,
  }) = CallSignal_Offer;
  const factory CallSignal.answer({
    required String sdp,
  }) = CallSignal_Answer;
  const factory CallSignal.ice({
    required String candidate,
    String? sdpMid,
    int? sdpMLineIndex,
  }) = CallSignal_Ice;
  const factory CallSignal.ringing() = CallSignal_Ringing;
  const factory CallSignal.busy() = CallSignal_Busy;
  const factory CallSignal.hangup({
    required HangupReason reason,
  }) = CallSignal_Hangup;
}

class CallSignalDto {
  final String callId;
  final String peer;
  final String media;
  final CallSignal signal;
  final BigInt createdAt;

  const CallSignalDto({
    required this.callId,
    required this.peer,
    required this.media,
    required this.signal,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      callId.hashCode ^
      peer.hashCode ^
      media.hashCode ^
      signal.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallSignalDto &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          peer == other.peer &&
          media == other.media &&
          signal == other.signal &&
          createdAt == other.createdAt;
}

class ChitthiDto {
  final String id;
  final String author;
  final String content;
  final BigInt createdAt;
  final String? replyTo;

  const ChitthiDto({
    required this.id,
    required this.author,
    required this.content,
    required this.createdAt,
    this.replyTo,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      author.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      replyTo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChitthiDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          author == other.author &&
          content == other.content &&
          createdAt == other.createdAt &&
          replyTo == other.replyTo;
}

class ComradeDto {
  final String npub;
  final String alias;
  final String? name;
  final bool online;
  final BigInt lastSeenAt;
  final bool peerMarkedUs;

  const ComradeDto({
    required this.npub,
    required this.alias,
    this.name,
    required this.online,
    required this.lastSeenAt,
    required this.peerMarkedUs,
  });

  @override
  int get hashCode =>
      npub.hashCode ^
      alias.hashCode ^
      name.hashCode ^
      online.hashCode ^
      lastSeenAt.hashCode ^
      peerMarkedUs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComradeDto &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          alias == other.alias &&
          name == other.name &&
          online == other.online &&
          lastSeenAt == other.lastSeenAt &&
          peerMarkedUs == other.peerMarkedUs;
}

class ContactDto {
  final String npub;
  final String alias;
  final String? name;
  final bool comrade;

  const ContactDto({
    required this.npub,
    required this.alias,
    this.name,
    required this.comrade,
  });

  @override
  int get hashCode =>
      npub.hashCode ^ alias.hashCode ^ name.hashCode ^ comrade.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactDto &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          alias == other.alias &&
          name == other.name &&
          comrade == other.comrade;
}

class ConversationDto {
  final String peer;
  final String? alias;
  final String? peerName;
  final String lastMessage;
  final BigInt lastAt;
  final bool lastOutgoing;
  final bool comrade;
  final bool online;

  const ConversationDto({
    required this.peer,
    this.alias,
    this.peerName,
    required this.lastMessage,
    required this.lastAt,
    required this.lastOutgoing,
    required this.comrade,
    required this.online,
  });

  @override
  int get hashCode =>
      peer.hashCode ^
      alias.hashCode ^
      peerName.hashCode ^
      lastMessage.hashCode ^
      lastAt.hashCode ^
      lastOutgoing.hashCode ^
      comrade.hashCode ^
      online.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationDto &&
          runtimeType == other.runtimeType &&
          peer == other.peer &&
          alias == other.alias &&
          peerName == other.peerName &&
          lastMessage == other.lastMessage &&
          lastAt == other.lastAt &&
          lastOutgoing == other.lastOutgoing &&
          comrade == other.comrade &&
          online == other.online;
}

class CrisisResourceDto {
  final String name;
  final String contact;
  final String note;

  const CrisisResourceDto({
    required this.name,
    required this.contact,
    required this.note,
  });

  @override
  int get hashCode => name.hashCode ^ contact.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrisisResourceDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          contact == other.contact &&
          note == other.note;
}

class DirectMessageDto {
  final String id;
  final String sender;
  final String content;
  final BigInt createdAt;
  final List<UpiIntentDto> upiIntents;
  final String? replyTo;
  final SharedNoteDto? sharedNote;

  const DirectMessageDto({
    required this.id,
    required this.sender,
    required this.content,
    required this.createdAt,
    required this.upiIntents,
    this.replyTo,
    this.sharedNote,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sender.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      upiIntents.hashCode ^
      replyTo.hashCode ^
      sharedNote.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DirectMessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sender == other.sender &&
          content == other.content &&
          createdAt == other.createdAt &&
          upiIntents == other.upiIntents &&
          replyTo == other.replyTo &&
          sharedNote == other.sharedNote;
}

class FoundProfileDto {
  final String npub;
  final String? name;
  final String? about;
  final String? picture;
  final String? nip05;

  const FoundProfileDto({
    required this.npub,
    this.name,
    this.about,
    this.picture,
    this.nip05,
  });

  @override
  int get hashCode =>
      npub.hashCode ^
      name.hashCode ^
      about.hashCode ^
      picture.hashCode ^
      nip05.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FoundProfileDto &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          name == other.name &&
          about == other.about &&
          picture == other.picture &&
          nip05 == other.nip05;
}

@freezed
sealed class HandoffSignal with _$HandoffSignal {
  const HandoffSignal._();

  const factory HandoffSignal.offer({
    required AttachmentHandoff attachment,
  }) = HandoffSignal_Offer;
  const factory HandoffSignal.accept() = HandoffSignal_Accept;
  const factory HandoffSignal.decline() = HandoffSignal_Decline;
  const factory HandoffSignal.refuse({
    required RefusalReason reason,
  }) = HandoffSignal_Refuse;
  const factory HandoffSignal.withdraw() = HandoffSignal_Withdraw;
  const factory HandoffSignal.transport({
    required TransferSignal signal,
  }) = HandoffSignal_Transport;
}

enum HangupReason {
  normal,
  declined,
  busy,
  missed,
  cancelled,
  failed,
  unknown,
  ;
}

enum IcePathKind {
  host,
  serverReflexive,
  relay,
  unknown,
  ;
}

class IceServerDto {
  final List<String> urls;
  final String? username;
  final String? credential;

  const IceServerDto({
    required this.urls,
    this.username,
    this.credential,
  });

  @override
  int get hashCode => urls.hashCode ^ username.hashCode ^ credential.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IceServerDto &&
          runtimeType == other.runtimeType &&
          urls == other.urls &&
          username == other.username &&
          credential == other.credential;
}

enum IceStrategy {
  stunOnly,
  stunAndTurn,
  ;
}

class IdentityDto {
  final String npub;
  final bool hasSecret;

  const IdentityDto({
    required this.npub,
    required this.hasSecret,
  });

  @override
  int get hashCode => npub.hashCode ^ hasSecret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityDto &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          hasSecret == other.hasSecret;
}

class JournalEntryDto {
  final String id;
  final String? title;
  final String text;
  final String? mood;
  final JournalRecordingDto? recording;
  final BigInt createdAt;

  const JournalEntryDto({
    required this.id,
    this.title,
    required this.text,
    this.mood,
    this.recording,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      text.hashCode ^
      mood.hashCode ^
      recording.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JournalEntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          text == other.text &&
          mood == other.mood &&
          recording == other.recording &&
          createdAt == other.createdAt;
}

class JournalRecordingDto {
  final String fileName;
  final String mime;
  final BigInt durationMs;
  final BigInt sizeBytes;

  const JournalRecordingDto({
    required this.fileName,
    required this.mime,
    required this.durationMs,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      fileName.hashCode ^
      mime.hashCode ^
      durationMs.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JournalRecordingDto &&
          runtimeType == other.runtimeType &&
          fileName == other.fileName &&
          mime == other.mime &&
          durationMs == other.durationMs &&
          sizeBytes == other.sizeBytes;
}

class LinkPreviewDto {
  final String url;
  final String canonicalUrl;
  final String? title;
  final String? description;
  final String? siteName;
  final PreviewKindDto kind;
  final String? displayDomain;

  const LinkPreviewDto({
    required this.url,
    required this.canonicalUrl,
    this.title,
    this.description,
    this.siteName,
    required this.kind,
    this.displayDomain,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      canonicalUrl.hashCode ^
      title.hashCode ^
      description.hashCode ^
      siteName.hashCode ^
      kind.hashCode ^
      displayDomain.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkPreviewDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          canonicalUrl == other.canonicalUrl &&
          title == other.title &&
          description == other.description &&
          siteName == other.siteName &&
          kind == other.kind &&
          displayDomain == other.displayDomain;
}

class MediaBytesDto {
  final String mimeType;
  final String base64;

  const MediaBytesDto({
    required this.mimeType,
    required this.base64,
  });

  @override
  int get hashCode => mimeType.hashCode ^ base64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaBytesDto &&
          runtimeType == other.runtimeType &&
          mimeType == other.mimeType &&
          base64 == other.base64;
}

class MediaMessageDto {
  final String eventId;
  final String url;
  final String mimeType;
  final String caption;
  final String sender;
  final BigInt createdAt;
  final BigInt size;
  final bool outgoing;

  const MediaMessageDto({
    required this.eventId,
    required this.url,
    required this.mimeType,
    required this.caption,
    required this.sender,
    required this.createdAt,
    required this.size,
    required this.outgoing,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      url.hashCode ^
      mimeType.hashCode ^
      caption.hashCode ^
      sender.hashCode ^
      createdAt.hashCode ^
      size.hashCode ^
      outgoing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaMessageDto &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          url == other.url &&
          mimeType == other.mimeType &&
          caption == other.caption &&
          sender == other.sender &&
          createdAt == other.createdAt &&
          size == other.size &&
          outgoing == other.outgoing;
}

class MeshStatusDto {
  final bool active;
  final BigInt peerCount;

  const MeshStatusDto({
    required this.active,
    required this.peerCount,
  });

  @override
  int get hashCode => active.hashCode ^ peerCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeshStatusDto &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          peerCount == other.peerCount;
}

class MessageActionState {
  final bool starred;
  final bool pinned;

  const MessageActionState({
    required this.starred,
    required this.pinned,
  });

  @override
  int get hashCode => starred.hashCode ^ pinned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageActionState &&
          runtimeType == other.runtimeType &&
          starred == other.starred &&
          pinned == other.pinned;
}

enum MessageAuthor {
  human,
  tara,
  ;
}

class MessageDto {
  final String id;
  final String peer;
  final String content;
  final BigInt createdAt;
  final bool outgoing;
  final MessageAuthor author;
  final String? status;
  final String? replyTo;
  final SharedNoteDto? sharedNote;
  final LinkPreviewDto? linkPreview;
  final bool forwarded;
  final MessageActionState actions;

  const MessageDto({
    required this.id,
    required this.peer,
    required this.content,
    required this.createdAt,
    required this.outgoing,
    required this.author,
    this.status,
    this.replyTo,
    this.sharedNote,
    this.linkPreview,
    required this.forwarded,
    required this.actions,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      peer.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      outgoing.hashCode ^
      author.hashCode ^
      status.hashCode ^
      replyTo.hashCode ^
      sharedNote.hashCode ^
      linkPreview.hashCode ^
      forwarded.hashCode ^
      actions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          peer == other.peer &&
          content == other.content &&
          createdAt == other.createdAt &&
          outgoing == other.outgoing &&
          author == other.author &&
          status == other.status &&
          replyTo == other.replyTo &&
          sharedNote == other.sharedNote &&
          linkPreview == other.linkPreview &&
          forwarded == other.forwarded &&
          actions == other.actions;
}

class MessageRequestDto {
  final String peer;
  final String lastMessage;
  final BigInt lastAt;

  const MessageRequestDto({
    required this.peer,
    required this.lastMessage,
    required this.lastAt,
  });

  @override
  int get hashCode => peer.hashCode ^ lastMessage.hashCode ^ lastAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageRequestDto &&
          runtimeType == other.runtimeType &&
          peer == other.peer &&
          lastMessage == other.lastMessage &&
          lastAt == other.lastAt;
}

class MetricDto {
  final String key;
  final BigInt value;

  const MetricDto({
    required this.key,
    required this.value,
  });

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetricDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

@freezed
sealed class MusicLink with _$MusicLink {
  const MusicLink._();

  const factory MusicLink.spotify({
    required String trackId,
  }) = MusicLink_Spotify;
  const factory MusicLink.appleMusic({
    required String storefront,
    required String trackId,
  }) = MusicLink_AppleMusic;
  const factory MusicLink.youtube({
    required String videoId,
  }) = MusicLink_Youtube;
}

class PeerProfileDto {
  final String npub;
  final String alias;
  final String? name;
  final String? about;
  final String? picture;
  final String? nip05;
  final String? lud16;
  final bool avatarCached;
  final bool contact;
  final bool comrade;
  final bool blocked;
  final bool online;
  final BigInt lastSeenAt;
  final bool peerMarkedUs;
  final BigInt updatedAt;

  const PeerProfileDto({
    required this.npub,
    required this.alias,
    this.name,
    this.about,
    this.picture,
    this.nip05,
    this.lud16,
    required this.avatarCached,
    required this.contact,
    required this.comrade,
    required this.blocked,
    required this.online,
    required this.lastSeenAt,
    required this.peerMarkedUs,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      npub.hashCode ^
      alias.hashCode ^
      name.hashCode ^
      about.hashCode ^
      picture.hashCode ^
      nip05.hashCode ^
      lud16.hashCode ^
      avatarCached.hashCode ^
      contact.hashCode ^
      comrade.hashCode ^
      blocked.hashCode ^
      online.hashCode ^
      lastSeenAt.hashCode ^
      peerMarkedUs.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerProfileDto &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          alias == other.alias &&
          name == other.name &&
          about == other.about &&
          picture == other.picture &&
          nip05 == other.nip05 &&
          lud16 == other.lud16 &&
          avatarCached == other.avatarCached &&
          contact == other.contact &&
          comrade == other.comrade &&
          blocked == other.blocked &&
          online == other.online &&
          lastSeenAt == other.lastSeenAt &&
          peerMarkedUs == other.peerMarkedUs &&
          updatedAt == other.updatedAt;
}

class PresenceDto {
  final String peer;
  final bool online;
  final BigInt lastSeenAt;
  final bool peerMarkedUs;

  const PresenceDto({
    required this.peer,
    required this.online,
    required this.lastSeenAt,
    required this.peerMarkedUs,
  });

  @override
  int get hashCode =>
      peer.hashCode ^
      online.hashCode ^
      lastSeenAt.hashCode ^
      peerMarkedUs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresenceDto &&
          runtimeType == other.runtimeType &&
          peer == other.peer &&
          online == other.online &&
          lastSeenAt == other.lastSeenAt &&
          peerMarkedUs == other.peerMarkedUs;
}

enum PreviewKindDto {
  article,
  photo,
  video,
  profile,
  unknown,
  ;
}

class ProfileDto {
  final String npub;
  final String? username;
  final String? about;
  final String? picture;
  final bool avatarCached;

  const ProfileDto({
    required this.npub,
    this.username,
    this.about,
    this.picture,
    required this.avatarCached,
  });

  @override
  int get hashCode =>
      npub.hashCode ^
      username.hashCode ^
      about.hashCode ^
      picture.hashCode ^
      avatarCached.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileDto &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          username == other.username &&
          about == other.about &&
          picture == other.picture &&
          avatarCached == other.avatarCached;
}

class ReactionDto {
  final String targetId;
  final String peer;
  final String reactor;
  final String emoji;
  final BigInt createdAt;
  final bool outgoing;

  const ReactionDto({
    required this.targetId,
    required this.peer,
    required this.reactor,
    required this.emoji,
    required this.createdAt,
    required this.outgoing,
  });

  @override
  int get hashCode =>
      targetId.hashCode ^
      peer.hashCode ^
      reactor.hashCode ^
      emoji.hashCode ^
      createdAt.hashCode ^
      outgoing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReactionDto &&
          runtimeType == other.runtimeType &&
          targetId == other.targetId &&
          peer == other.peer &&
          reactor == other.reactor &&
          emoji == other.emoji &&
          createdAt == other.createdAt &&
          outgoing == other.outgoing;
}

class Recording {
  final String? isrc;
  final String title;
  final String artist;
  final String? album;

  const Recording({
    this.isrc,
    required this.title,
    required this.artist,
    this.album,
  });

  @override
  int get hashCode =>
      isrc.hashCode ^ title.hashCode ^ artist.hashCode ^ album.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Recording &&
          runtimeType == other.runtimeType &&
          isrc == other.isrc &&
          title == other.title &&
          artist == other.artist &&
          album == other.album;
}

@freezed
sealed class RefusalReason with _$RefusalReason {
  const RefusalReason._();

  const factory RefusalReason.relayForbidden() = RefusalReason_RelayForbidden;
  const factory RefusalReason.tooLargeForRelay({
    required BigInt limit,
  }) = RefusalReason_TooLargeForRelay;
  const factory RefusalReason.pathUnknown() = RefusalReason_PathUnknown;
}

@freezed
sealed class RelayPolicy with _$RelayPolicy {
  const RelayPolicy._();

  const factory RelayPolicy.directOnly() = RelayPolicy_DirectOnly;
  const factory RelayPolicy.underBytes({
    required BigInt limit,
  }) = RelayPolicy_UnderBytes;
  const factory RelayPolicy.askEachTime() = RelayPolicy_AskEachTime;
  const factory RelayPolicy.always() = RelayPolicy_Always;
}

class RideSignalDto {
  final String peer;
  final String? name;
  final String kind;
  final String? phrase;
  final String? maneuver;
  final int? distanceM;
  final String? note;
  final String urgency;
  final BigInt createdAt;

  const RideSignalDto({
    required this.peer,
    this.name,
    required this.kind,
    this.phrase,
    this.maneuver,
    this.distanceM,
    this.note,
    required this.urgency,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      peer.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      phrase.hashCode ^
      maneuver.hashCode ^
      distanceM.hashCode ^
      note.hashCode ^
      urgency.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RideSignalDto &&
          runtimeType == other.runtimeType &&
          peer == other.peer &&
          name == other.name &&
          kind == other.kind &&
          phrase == other.phrase &&
          maneuver == other.maneuver &&
          distanceM == other.distanceM &&
          note == other.note &&
          urgency == other.urgency &&
          createdAt == other.createdAt;
}

class ShareOffer {
  final BigInt totalBytes;
  final int chunkBytes;
  final String sha256;
  final BigInt durationMs;

  const ShareOffer({
    required this.totalBytes,
    required this.chunkBytes,
    required this.sha256,
    required this.durationMs,
  });

  @override
  int get hashCode =>
      totalBytes.hashCode ^
      chunkBytes.hashCode ^
      sha256.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareOffer &&
          runtimeType == other.runtimeType &&
          totalBytes == other.totalBytes &&
          chunkBytes == other.chunkBytes &&
          sha256 == other.sha256 &&
          durationMs == other.durationMs;
}

@freezed
sealed class ShareSignal with _$ShareSignal {
  const ShareSignal._();

  const factory ShareSignal.ask() = ShareSignal_Ask;
  const factory ShareSignal.offer({
    required ShareOffer offer,
  }) = ShareSignal_Offer;
  const factory ShareSignal.accept() = ShareSignal_Accept;
  const factory ShareSignal.refuse({
    required RefusalReason reason,
  }) = ShareSignal_Refuse;
  const factory ShareSignal.transport({
    required TransferSignal signal,
  }) = ShareSignal_Transport;
}

class SharedNoteDto {
  final String text;
  final String? mood;

  const SharedNoteDto({
    required this.text,
    this.mood,
  });

  @override
  int get hashCode => text.hashCode ^ mood.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SharedNoteDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          mood == other.mood;
}

enum StateChange {
  played,
  paused,
  seeked,
  pausedAndSeeked,
  unchanged,
  ;
}

@freezed
sealed class SyncVerdict with _$SyncVerdict {
  const SyncVerdict._();

  const factory SyncVerdict.hold() = SyncVerdict_Hold;
  const factory SyncVerdict.adopt({
    required BigInt posMs,
    required bool playing,
    required BigInt seq,
  }) = SyncVerdict_Adopt;
  const factory SyncVerdict.nudge({
    required double rate,
  }) = SyncVerdict_Nudge;
  const factory SyncVerdict.seek({
    required BigInt posMs,
  }) = SyncVerdict_Seek;
}

class TaraMessageDto {
  final String id;
  final String text;
  final bool fromTara;
  final bool crisis;
  final BigInt createdAt;

  const TaraMessageDto({
    required this.id,
    required this.text,
    required this.fromTara,
    required this.crisis,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      text.hashCode ^
      fromTara.hashCode ^
      crisis.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaraMessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          fromTara == other.fromTara &&
          crisis == other.crisis &&
          createdAt == other.createdAt;
}

class ThreadDto {
  final String rootId;
  final String peer;
  final String? topicSlug;
  final List<MessageDto> messages;
  final List<MediaMessageDto> media;

  const ThreadDto({
    required this.rootId,
    required this.peer,
    this.topicSlug,
    required this.messages,
    required this.media,
  });

  @override
  int get hashCode =>
      rootId.hashCode ^
      peer.hashCode ^
      topicSlug.hashCode ^
      messages.hashCode ^
      media.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadDto &&
          runtimeType == other.runtimeType &&
          rootId == other.rootId &&
          peer == other.peer &&
          topicSlug == other.topicSlug &&
          messages == other.messages &&
          media == other.media;
}

class ThreadSummaryDto {
  final String rootId;
  final String peer;
  final String? topicSlug;
  final String preview;
  final bool rootIsMedia;
  final bool rootMissing;
  final BigInt startedAt;
  final int replyCount;
  final BigInt lastAt;
  final bool unread;

  const ThreadSummaryDto({
    required this.rootId,
    required this.peer,
    this.topicSlug,
    required this.preview,
    required this.rootIsMedia,
    required this.rootMissing,
    required this.startedAt,
    required this.replyCount,
    required this.lastAt,
    required this.unread,
  });

  @override
  int get hashCode =>
      rootId.hashCode ^
      peer.hashCode ^
      topicSlug.hashCode ^
      preview.hashCode ^
      rootIsMedia.hashCode ^
      rootMissing.hashCode ^
      startedAt.hashCode ^
      replyCount.hashCode ^
      lastAt.hashCode ^
      unread.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadSummaryDto &&
          runtimeType == other.runtimeType &&
          rootId == other.rootId &&
          peer == other.peer &&
          topicSlug == other.topicSlug &&
          preview == other.preview &&
          rootIsMedia == other.rootIsMedia &&
          rootMissing == other.rootMissing &&
          startedAt == other.startedAt &&
          replyCount == other.replyCount &&
          lastAt == other.lastAt &&
          unread == other.unread;
}

class TogetherCommandDto {
  final String sessionId;
  final BigInt posMs;
  final bool playing;
  final StateChange change;
  final BigInt applyInMs;

  const TogetherCommandDto({
    required this.sessionId,
    required this.posMs,
    required this.playing,
    required this.change,
    required this.applyInMs,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      posMs.hashCode ^
      playing.hashCode ^
      change.hashCode ^
      applyInMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TogetherCommandDto &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          posMs == other.posMs &&
          playing == other.playing &&
          change == other.change &&
          applyInMs == other.applyInMs;
}

@freezed
sealed class TogetherContent with _$TogetherContent {
  const TogetherContent._();

  const factory TogetherContent.localFile({
    required BigInt durationMs,
    Recording? recording,
  }) = TogetherContent_LocalFile;
  const factory TogetherContent.youtube({
    required String videoId,
  }) = TogetherContent_Youtube;
  const factory TogetherContent.service({
    required MusicLink link,
    Recording? recording,
  }) = TogetherContent_Service;
  const factory TogetherContent.stream({
    required String url,
    Recording? recording,
    BigInt? durationMs,
  }) = TogetherContent_Stream;
}

class TogetherCorrectionDto {
  final String sessionId;
  final SyncVerdict verdict;
  final PlatformInt64 driftMs;
  final BigInt qualityMs;

  const TogetherCorrectionDto({
    required this.sessionId,
    required this.verdict,
    required this.driftMs,
    required this.qualityMs,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      verdict.hashCode ^
      driftMs.hashCode ^
      qualityMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TogetherCorrectionDto &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          verdict == other.verdict &&
          driftMs == other.driftMs &&
          qualityMs == other.qualityMs;
}

class TogetherInviteDto {
  final String sessionId;
  final String peer;
  final TogetherContent content;
  final BigInt posMs;
  final bool playing;
  final BigInt createdAt;

  const TogetherInviteDto({
    required this.sessionId,
    required this.peer,
    required this.content,
    required this.posMs,
    required this.playing,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      peer.hashCode ^
      content.hashCode ^
      posMs.hashCode ^
      playing.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TogetherInviteDto &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          peer == other.peer &&
          content == other.content &&
          posMs == other.posMs &&
          playing == other.playing &&
          createdAt == other.createdAt;
}

class TogetherSessionDto {
  final String sessionId;
  final String peer;
  final TogetherContent content;
  final bool weLead;
  final bool joined;
  final BigInt posMs;
  final bool playing;

  const TogetherSessionDto({
    required this.sessionId,
    required this.peer,
    required this.content,
    required this.weLead,
    required this.joined,
    required this.posMs,
    required this.playing,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      peer.hashCode ^
      content.hashCode ^
      weLead.hashCode ^
      joined.hashCode ^
      posMs.hashCode ^
      playing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TogetherSessionDto &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          peer == other.peer &&
          content == other.content &&
          weLead == other.weLead &&
          joined == other.joined &&
          posMs == other.posMs &&
          playing == other.playing;
}

class TogetherShareDto {
  final String sessionId;
  final String peer;
  final ShareSignal signal;

  const TogetherShareDto({
    required this.sessionId,
    required this.peer,
    required this.signal,
  });

  @override
  int get hashCode => sessionId.hashCode ^ peer.hashCode ^ signal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TogetherShareDto &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          peer == other.peer &&
          signal == other.signal;
}

class TopicDto {
  final String slug;
  final String name;
  final String peer;
  final String createdBy;
  final bool mine;
  final BigInt createdAt;
  final bool closed;
  final int threadCount;
  final int messageCount;
  final BigInt lastActivityAt;

  const TopicDto({
    required this.slug,
    required this.name,
    required this.peer,
    required this.createdBy,
    required this.mine,
    required this.createdAt,
    required this.closed,
    required this.threadCount,
    required this.messageCount,
    required this.lastActivityAt,
  });

  @override
  int get hashCode =>
      slug.hashCode ^
      name.hashCode ^
      peer.hashCode ^
      createdBy.hashCode ^
      mine.hashCode ^
      createdAt.hashCode ^
      closed.hashCode ^
      threadCount.hashCode ^
      messageCount.hashCode ^
      lastActivityAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TopicDto &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          name == other.name &&
          peer == other.peer &&
          createdBy == other.createdBy &&
          mine == other.mine &&
          createdAt == other.createdAt &&
          closed == other.closed &&
          threadCount == other.threadCount &&
          messageCount == other.messageCount &&
          lastActivityAt == other.lastActivityAt;
}

@freezed
sealed class TransferSignal with _$TransferSignal {
  const TransferSignal._();

  const factory TransferSignal.offer({
    required String sdp,
  }) = TransferSignal_Offer;
  const factory TransferSignal.answer({
    required String sdp,
  }) = TransferSignal_Answer;
  const factory TransferSignal.ice({
    required String candidate,
    String? sdpMid,
    int? sdpMLineIndex,
  }) = TransferSignal_Ice;
}

@freezed
sealed class TransferVerdict with _$TransferVerdict {
  const TransferVerdict._();

  const factory TransferVerdict.allow() = TransferVerdict_Allow;
  const factory TransferVerdict.needsConsent({
    required BigInt relayedBytes,
  }) = TransferVerdict_NeedsConsent;
  const factory TransferVerdict.refuse({
    required RefusalReason reason,
  }) = TransferVerdict_Refuse;
}

class TurnServerStatusDto {
  final bool configured;
  final String? url;

  const TurnServerStatusDto({
    required this.configured,
    this.url,
  });

  @override
  int get hashCode => configured.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TurnServerStatusDto &&
          runtimeType == other.runtimeType &&
          configured == other.configured &&
          url == other.url;
}

@freezed
sealed class UiError with _$UiError implements FrbException {
  const UiError._();

  const factory UiError.unknownWorkspace(
    String field0,
  ) = UiError_UnknownWorkspace;
  const factory UiError.transition(
    String field0,
  ) = UiError_Transition;
  const factory UiError.noIdentity() = UiError_NoIdentity;
  const factory UiError.storeLocked() = UiError_StoreLocked;
  const factory UiError.crypto(
    String field0,
  ) = UiError_Crypto;
  const factory UiError.storage(
    String field0,
  ) = UiError_Storage;
  const factory UiError.vaultLocked() = UiError_VaultLocked;
  const factory UiError.engine(
    String field0,
  ) = UiError_Engine;
  const factory UiError.catalogue(
    String field0,
  ) = UiError_Catalogue;
  const factory UiError.download(
    String field0,
  ) = UiError_Download;
  const factory UiError.catalogueUnavailable() = UiError_CatalogueUnavailable;
  const factory UiError.travel(
    String field0,
  ) = UiError_Travel;
  const factory UiError.travelUnavailable() = UiError_TravelUnavailable;
}

class UpiIntentDto {
  final double amountInr;
  final String vpa;
  final String uri;

  const UpiIntentDto({
    required this.amountInr,
    required this.vpa,
    required this.uri,
  });

  @override
  int get hashCode => amountInr.hashCode ^ vpa.hashCode ^ uri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpiIntentDto &&
          runtimeType == other.runtimeType &&
          amountInr == other.amountInr &&
          vpa == other.vpa &&
          uri == other.uri;
}

class WorkspaceDto {
  final String key;
  final String label;
  final bool active;
  final bool relayConnected;
  final bool meshActive;
  final bool coupleSandbox;

  const WorkspaceDto({
    required this.key,
    required this.label,
    required this.active,
    required this.relayConnected,
    required this.meshActive,
    required this.coupleSandbox,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      active.hashCode ^
      relayConnected.hashCode ^
      meshActive.hashCode ^
      coupleSandbox.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          active == other.active &&
          relayConnected == other.relayConnected &&
          meshActive == other.meshActive &&
          coupleSandbox == other.coupleSandbox;
}
